/*
  All interface text lives here, so wording can be edited in one place.

  Tone: a calm, clear learning platform. Warm and encouraging, like a good teacher talking to an
  11 to 15 year old. Short sentences, no slang, no game language (no points, credits or "unlocked!"),
  and no em dashes. At most one exclamation mark per screen, and only for a real milestone.
  The detective theme lives in the nouns (Case, Clue, Evidence, Evidence Board, Interrogation Room,
  Notebook, Verdict). Every theme word should make sense from the sentence around it.

  Lesson and quiz content (readings, questions, hints, explanations) is course content, not interface
  text. It lives in src/data.
*/

/** "1 lesson", "3 lessons" */
export const plural = (n: number, one: string, many = `${one}s`) => `${n} ${n === 1 ? one : many}`;

export const copy = {
  brand: {
    name: "CaseFile",
    logoLabel: "CaseFile, go to the Desk",
    homeLabel: "CaseFile, home",
  },

  common: {
    skipLink: "Skip to main content",
    start: "Start",
    continue: "Continue",
    save: "Save",
    next: "Next",
    back: "Back",
    submit: "Submit",
    review: "Review",
    cancel: "Cancel",
    skip: "Skip",
    done: "Done",
    close: "Close",
    tryAgain: "Try again",
    loading: "Loading",
    delete: "Delete",
    open: "Open",
    show: "Show",
    hide: "Hide",
    min: (n: number) => `${n} min`,
    aboutMin: (n: number) => `About ${n} min`,
    studyItems: (n: number) => `${n} ${n === 1 ? "piece" : "pieces"} of evidence`,
  },

  meta: {
    siteTitle: "CaseFile | A learning platform for ages 11 to 15",
    siteDescription:
      "CaseFile is a learning platform for ages 11 to 15. Each subject is a case, made of short lessons, study material and quizzes.",
    desk: "The Desk",
    cases: "Cases",
    board: "Evidence Board",
    notebook: "Notebook",
    lab: "The Lab",
    join: "Set up your profile",
    about: "About me",
    clueNotFound: "Clue not found",
    caseNotFound: "Case not found",
    interrogation: "Interrogation Room",
    verdict: "The Verdict",
    notFound: "Page not found",
    styleguide: "Style guide",
    families: "For parents and teachers",
    subjects: "Subjects",
    videos: "Videos",
    studio: "Editor desk",
  },

  nav: {
    main: "Main",
    items: {
      desk: { label: "Desk", short: "Desk" },
      cases: { label: "Cases", short: "Cases" },
      board: { label: "Evidence Board", short: "Board" },
      notebook: { label: "Notebook", short: "Notebook" },
      lab: { label: "Lab", short: "Lab" },
      videos: { label: "Videos", short: "Videos" },
    },
  },

  /** Level and streak are small, quiet labels */
  level: {
    label: (name: string) => `Level: ${name}`,
    streak: (days: number) => `Study streak: ${plural(days, "day")}`,
    nextLevel: (remaining: number, next: string) =>
      `Complete ${plural(remaining, "more lesson")} to reach ${next}.`,
    topLevel: "You have reached the top level.",
    howItWorks: "Your level goes up as you complete lessons and close cases.",
  },

  /** Case status tags. "Cold case" is a small tag, always with a plain sentence next to it. */
  status: {
    open: "Not started",
    active: "In progress",
    cold: "Cold case",
    closed: "Closed",
    aria: (label: string) => `Case status: ${label}`,
    preview: "(preview case)",
  },

  evidenceKinds: {
    reading: "Reading",
    video: "Video",
    diagram: "Diagram",
    practice: "Practice set",
  },

  /** Hints are help, not a cost */
  hints: {
    footnote: "Hints are here to help. Use them whenever you like.",
    get: "Get a hint",
    getNumbered: (n: number) => `Get hint ${n}`,
    showExplanation: "Show the full explanation",
    fullExplanation: "Full explanation",
    theAnswer: "The answer:",
    levelNames: ["A small nudge", "Where to look", "Step by step"] as const,
    noteLabel: (n: number, name: string) => `Hint ${n} of 3 (${name})`,
    lookHere: (title: string) => `Go back to “${title}”. The answer is in there.`,
    openEvidence: "Open that evidence",
    jumpToIt: "Jump to it",
    lookBackGeneric: "Look back over the evidence for this clue. Read the parts that mention the key word in the question.",
  },

  desk: {
    label: "The Desk",
    welcomeBack: (name: string) => `Welcome back, ${name}`,
    welcomeGuest: "Welcome to CaseFile",
    subtitle: "Here is what to work on today.",
    guestSubtitle: "You are browsing as a guest. Set up a profile to save your progress.",
    setUpProfile: "Set up your profile",
    loading: "Loading your desk",
    progress: {
      heading: "Your progress",
      streak: "Study streak",
      streakValue: (n: number) => plural(n, "day"),
      lessons: "Lessons completed",
      closed: "Cases closed",
    },
    lead: {
      label: "Up next",
      clueHeading: (n: number, title: string) => `Clue ${n}: ${title}`,
      stepOf: (n: number, total: number) => `Clue ${n} of ${total}`,
      verdictHeading: "You have completed every lesson",
      verdictText: (title: string) => `You can now take the Verdict, the final test for ${title}.`,
      startVerdict: "Start the Verdict",
      allClosedHeading: "Every case is closed",
      allClosedText: "Check back soon. New cases are on the way.",
    },
    revise: {
      heading: "Time to revise",
      intro: "You have not studied these topics for a while. A short review helps you remember them.",
      line: (topic: string, days: number) => `Time to revise: ${topic}. Last studied ${plural(days, "day")} ago.`,
      detail: (done: number, total: number) => `You had completed ${done} of ${plural(total, "lesson")}.`,
      start: "Start review",
      openCase: "Open case",
      empty: "Nothing to revise yet. A case you have not opened for 7 days will show up here.",
    },
    inProgress: {
      heading: "Cases in progress",
      empty: "No cases in progress yet. Start with the lesson above and your case will appear here.",
    },
    notStarted: { heading: "Not started yet", seeAll: "See all cases" },
  },

  library: {
    label: "The case library",
    title: "Cases",
    intro: "Choose a subject to study. Each case is a set of short lessons with a final test at the end.",
    filterGroup: (what: string) => `Filter by ${what}`,
    subject: "Subject",
    status: "Status",
    all: "All",
    allCases: "All cases",
    browseSubjects: "Browse by subject, chapter and lesson",
    showing: (n: number) => `Showing ${plural(n, "case")}`,
    loading: "Loading cases",
    emptyTitle: "No cases match",
    emptyText: "Try a different subject or status.",
    clear: "Clear filters",
  },

  folder: {
    caseNo: (n: string) => `NO. ${n}`,
    cta: { open: "Start", active: "Continue", cold: "Review", closed: "View results" },
    lessonsDone: (done: number, total: number) => `${done} of ${plural(total, "lesson")} completed`,
    progressLabel: (title: string) => `${title}, progress`,
    // The papers that slide out of a folder on hover
    peekBrief: "Case brief",
    peekNext: "Next lesson",
    peekFinal: "Final test",
    peekFinalText: "All lessons done. The final test is next.",
    peekClosed: "Case closed",
    peekNote: (done: number, total: number) => (done === 0 ? "No lessons done yet" : done === total ? "Every lesson done" : `${done} of ${total} lessons done`),
    tapAgain: "Tap again to open",
  },

  caseFile: {
    allCases: "All cases",
    caseNo: (n: string) => `Case no. ${n}`,
    lessonsDone: (done: number, total: number) => `${done} of ${plural(total, "lesson")} completed`,
    tabsLabel: "Case file sections",
    progressLabel: "Case progress",
    tabs: { brief: "Brief", clues: "Clues", evidence: "Evidence", notes: "Notes" },
    brief: {
      previewTitle: "Preview case.",
      previewText:
        "The lessons for this case are still being written. You can look around, but you can only complete lessons in the Vanishing Puddle case.",
      about: "About this case",
      goal: "Goal",
      learn: "By the end you will be able to",
      how: "How this case works",
      howText: (n: number) =>
        n === 1
          ? "This case has 1 lesson, called a clue. It has study material, called evidence, and a few questions at the end. When you have completed it, you can take the Verdict, the final test that closes the case."
          : `This case has ${plural(n, "lesson")}, called clues. Complete them in order. Each clue has study material, called evidence, and a few questions at the end. When you have completed every clue, you can take the Verdict, the final test that closes the case.`,
      startFirst: "Start Clue 1",
      previewFirst: "Preview Clue 1",
      viewAll: "View all clues",
      viewResults: "View results",
      startVerdict: "Start the Verdict",
    },
    clues: {
      heading: "Clues",
      intro: "A clue is a lesson. Complete a clue to open the next one.",
    },
    clueCard: {
      label: (n: number) => `Clue ${n}`,
      stateDone: "completed",
      stateReady: "ready to start",
      stateLocked: "not open yet",
      completeFirst: (n: number) => `Complete clue ${n} first`,
      stamp: "Completed",
      start: "Start",
      preview: "Preview",
      review: "Review",
    },
    evidence: {
      heading: "Evidence",
      intro: "Study material for each clue: readings, diagrams, videos and practice sets.",
      itemsShow: (n: number) => `${n} items, show`,
      locked: "(not open yet)",
      lockedNote: "Available after you complete the clue before it",
      onBoard: "On your board",
    },
    notes: {
      heading: "Notes",
      intro: "Write down what you want to remember. Your notes also appear in the Notebook.",
      empty: "No notes for this case yet.",
    },
    finalTest: {
      lockedTitle: "Final test: not available yet",
      lockedText: (left: number) =>
        `Complete ${plural(left, "more lesson")} to take the Verdict, the final test for this case.`,
      lockedProgress: "Lessons completed toward the final test",
      readyTitle: "The final test is ready",
      readyText: "You have completed every lesson. You can now take the Verdict.",
      closedTitle: "Case closed",
      closedText: "You passed the Verdict.",
      start: "Start the Verdict",
      viewResults: "View results",
    },
  },

  lesson: {
    backToCase: "Back to the case file",
    position: (title: string, n: number, total: number) => `${title} · Clue ${n} of ${total}`,
    completed: "Completed",
    questionLabel: "Question for this clue",
    study: "Study the evidence",
    jumpTo: "Jump to evidence",
    evidenceLabel: (n: number, total: number, kind: string) => `Evidence ${n} of ${total} · ${kind}`,
    collect: "Collect evidence",
    collected: "Collected",
    collectHelp: "Pin this to your Evidence Board.",
    collectedHelp: "It is on your Evidence Board. Press the button again to remove it.",
    notesHeading: "Take notes",
    notesIntro: "Write down anything you want to remember. It is saved in your Notebook.",
    checkLabel: "Interrogation Room",
    checkHeading: "Ready to check what you know?",
    checkHeadingDone: "Want more practice?",
    checkText: (n: number) =>
      `${plural(n, "short question")}. Answer them to complete this clue. If you get stuck, hints are there to help.`,
    startQuestions: "Start the questions",
    reviewQuestions: "Review the questions",
    needHelp: "Need help first?",
    lockedTitle: "This clue is not open yet",
    lockedText: (n: number) => `Complete clue ${n} first. Then this one opens.`,
    goToClue: (n: number) => `Go to clue ${n}`,
    previewTitle: "This is a preview",
    previewText:
      "The lesson for this clue is still being written. Here is the evidence it will include. To try a full lesson now, open the Vanishing Puddle case.",
    previewOpenPuddle: "Open the Vanishing Puddle",
    evidenceSoon: "This evidence is on its way.",
    comingSoon: "Coming soon",
    loading: "Loading the clue",
    noticeHeading: "What to notice",
    transcript: "Read the transcript",
    stepOf: (n: number, total: number) => `Step ${n} of ${total}`,
    explainerLabel: "Animated explainer",
    play: "Play",
    pause: "Pause",
    playAgain: "Play again",
  },

  practice: {
    label: (n: number, total: number) => `Practice ${n} of ${total}`,
    doneTitle: "Practice complete",
    doneText: (right: number, total: number) => `You answered ${right} of ${total} correctly first time. That is a good warm-up.`,
    finish: "Finish practice",
    checkOrder: "Check order",
    orderCorrect: "That is the correct order.",
    orderPartial: (right: number, total: number) => `${right} of ${total} in the right place. Try moving the others.`,
    moveUp: (name: string) => `Move up: ${name}`,
    moveDown: (name: string) => `Move down: ${name}`,
    moved: (pos: number, total: number) => `Moved to position ${pos} of ${total}`,
    rightPlace: "Right place",
    wrongPlace: "Wrong place",
  },

  question: {
    position: (n: number, total: number) => `Question ${n} of ${total}`,
    lineupTag: "Suspect lineup: pick the correct idea",
    legendLineup: "Pick the idea that is correct",
    legendChoice: "Pick one answer",
    idea: (letter: string) => `Idea ${letter}`,
    stampWrong: "Not quite",
    stampRight: "Correct",
    notThisOne: "(not this one)",
    correctAnswer: "(correct answer)",
    wrongTitle: "Not quite.",
    wrongDefault: "Have another look and try again.",
    missedDefault: "That was not the one.",
    rightFirst: "Right first time.",
    rightLater: "That's right.",
    rightAnswer: "The right answer:",
    nextQuestion: "Next question",
    finish: "Finish",
  },

  room: {
    label: "Interrogation Room",
    help: "The Interrogation Room is the quiz area. You answer short questions to check what you know. Getting one wrong is fine, because it shows what to practise.",
    helpLabel: "What is the Interrogation Room?",
    reviewTitle: (topic: string) => `${topic}: review`,
    clueTitle: (n: number, title: string) => `Clue ${n}: ${title}`,
    backToClue: "Back to the clue",
    backToCase: "Back to the case file",
    loading: "Loading",
    lockedTitle: "This clue is not open yet",
    lockedText: (n: number) => `Complete clue ${n} first. Then the questions open.`,
    result: {
      clueDone: (n: number) => `Clue ${n} completed`,
      reviewDone: "Review complete",
      firstTime: (right: number, total: number) => `${right} of ${total} answered correctly first time.`,
      factQuestions: "Answered first time",
      factProgress: "Case progress",
      factStatus: "Case status",
      factNext: "Next up",
      statusNote: "This case is no longer marked as a cold case.",
      statusValue: "In progress",
      nextClue: (n: number) => `Clue ${n}`,
      nextVerdict: "The Verdict",
      nextNote: "Whenever you are ready",
      lessonsDone: (done: number, total: number) => `${done} of ${plural(total, "lesson")} completed`,
      allDoneVerdict: "All lessons completed. Start the Verdict",
      nextClueButton: "Next clue",
      continueCase: "Continue the case",
      backToCase: "Back to the case file",
      toDesk: "Go to the Desk",
    },
  },

  verdict: {
    label: "The Verdict",
    back: "Back to the case file",
    lockedTitle: "The final test is not open yet",
    lockedText: (left: number) => `Complete ${plural(left, "more lesson")} to take the Verdict.`,
    finalTest: "Final test",
    introTitle: "The final test for this case",
    introText: "You have completed every lesson. This test checks what you have learned.",
    rules: {
      questions: (n: number) => `${plural(n, "question")}, one at a time.`,
      noHints: "There are no hints in the final test. You answer each question once.",
      needed: (n: number) => `Get ${n} or more right to close the case.`,
      retry: "If you do not pass, you can review the lessons and try again as many times as you need.",
    },
    alreadyClosed: (score: number) =>
      `You closed this case with ${score}%. You can take the Verdict again for practice. Your best score is kept.`,
    start: "Start the Verdict",
    again: "Take it again",
    nextQuestion: "Next question",
    seeResults: "See my results",
    notPassed: {
      title: "Not passed yet",
      score: (right: number, total: number, needed: number) =>
        `You got ${right} of ${total} right. You need ${needed} to close the case.`,
      text: (closed: boolean) =>
        `Review the lessons below, then try again. ${closed ? "Your case stays closed." : "You can try as many times as you need."}`,
      retry: "Try the Verdict again",
      back: "Back to the case file",
    },
    closed: {
      caseNo: (n: string) => `Case no. ${n}`,
      stamp: "Case closed",
      summary: (lessons: number, right: number, total: number) =>
        `Case closed. You completed all ${plural(lessons, "lesson")} and passed the final test with ${right} of ${total}.`,
      alreadyClosed: "You had already closed this case. Your best score is kept.",
    },
    breakdown: "Results by lesson",
    clueLabel: (n: number) => `Clue ${n}`,
    rightOf: (right: number, total: number) => `${right} of ${total} right`,
    allRight: "All right",
    scoreLabel: (n: number) => `Clue ${n} score`,
    reviewClue: "Review this clue",
    next: {
      heading: "Your next case",
      headingNone: "What next?",
      textPreview: "This one is a preview for now, but you can look at what is coming.",
      textFull: "Ready to learn something new? This case is next.",
      open: "Open the case",
      toDesk: "Go to the Desk",
      none: "You have closed every case we have. New ones are on the way.",
      lab: "See your progress in the Lab",
    },
  },

  board: {
    label: "Your pinboard",
    title: "Evidence Board",
    help: "The Evidence Board is a map of what you have studied. Connect cards that belong together to see how ideas link up.",
    helpLabel: "What is the Evidence Board?",
    intro: "Everything you collect is pinned here. Move the cards around, then connect related ideas with red string.",
    tidy: "Tidy up",
    loading: "Loading your board",
    emptyTitle: "Nothing pinned yet",
    emptyText: "Open a clue and press Collect evidence on anything useful. It will appear here.",
    toDesk: "Go to the Desk",
    browse: "Browse cases",
    suggestionLabel: "Suggestion",
    suggestion: (a: string, b: string) => `You haven’t connected “${a}” and “${b}” yet.`,
    showMe: "Show me the cards",
    later: "Maybe later",
    connectedLabel: "Connected",
    goodLink: (a: string, b: string, why: string) => `Good connection between “${a}” and “${b}”. ${why}`,
    plainLink: (a: string, b: string) =>
      `Connected “${a}” and “${b}”. If they do not belong together, you can remove the connection.`,
    already: "Those two cards are already connected.",
    needMore: "Collect a few more pieces of evidence, then you can start connecting ideas.",
    allConnectedLabel: "All connected",
    allConnected: "Every pair that belongs together is connected. Good work.",
    howHeading: "How the board works",
    howItems: [
      "Drag a card to move it. With a keyboard, focus a card and use the arrow keys.",
      "Drag from the red pin to another card to connect them. Or press one pin, then another card.",
      "Press a string to remove it, or use the list below the board.",
    ],
    counts: (cards: number, strings: number) =>
      `${cards} ${cards === 1 ? "card" : "cards"}, ${strings} ${strings === 1 ? "connection" : "connections"}`,
    listHeading: "Your connections",
    remove: "Remove",
    removeLabel: (a: string, b: string) => `Remove the connection between ${a} and ${b}`,
    connectedTo: "connected to",
    region: "Evidence board",
    connecting: (title: string) =>
      `Connecting from ${title}. Now press the pin or the card you want to connect it to.`,
    cancel: "Cancel",
    removeThis: "Remove this connection",
    stringBetween: (a: string, b: string) => `String between ${a} and ${b}`,
    cardLabel: (title: string, kind: string, n: number) =>
      `${title}. ${kind} from clue ${n}. Use the arrow keys to move this card.`,
    pinLabel: (title: string) => `Connect from ${title}. Then press another card’s pin.`,
    cardMeta: (n: number, caseNo: string) => `Clue ${n} · No. ${caseNo}`,
    kindShort: { reading: "Reading", video: "Video", diagram: "Diagram", practice: "Practice" },
  },

  lab: {
    label: "Your progress",
    title: "The Lab",
    intro: "See what you have learned, what could use more practice, and what to revise.",
    loading: "Loading the Lab",
    levelHeading: "Your level",
    allLevels: "All levels",
    levelStatus: { here: "you are here", reached: "reached", ahead: "not yet" },
    numbers: "Your numbers",
    stats: {
      streak: "Study streak",
      lessons: "Lessons completed",
      closed: "Cases closed",
      firstTime: "Answered correctly first time",
      evidence: "Evidence collected",
      notes: "Notes written",
      none: "None yet",
    },
    topics: {
      heading: "Strengths and topics to practise",
      emptyTitle: "Nothing to show yet",
      emptyText: "Finish a clue in the Interrogation Room and your results will appear here.",
      strongTitle: "You are strong in",
      weakTitle: "Needs more practice",
      strongEmpty: "Keep going. Your strongest topics will appear here.",
      weakEmpty: "Nothing here right now. Well done.",
      summary: (strong: string[], weak: string[]) => {
        const join = (xs: string[]) => (xs.length <= 1 ? xs.join("") : `${xs.slice(0, -1).join(", ")} and ${xs[xs.length - 1]}`);
        const parts: string[] = [];
        if (strong.length) parts.push(`You’re strong in ${join(strong)}.`);
        if (weak.length) parts.push(`You could use more practice on ${join(weak)}.`);
        return parts.join(" ");
      },
      result: (right: number, total: number, pct: number) => `${right} of ${total} answered correctly (${pct}%)`,
      review: "Review this clue",
      accuracyLabel: (title: string) => `${title}, accuracy`,
    },
    revise: {
      heading: "Time to revise",
      none: (days: number) => `All your cases are up to date. A case needs revision after ${plural(days, "day")} without studying.`,
      cooling: (topic: string, days: number, left: number) =>
        `${topic}: you have not studied this for ${plural(days, "day")}. Review it within ${plural(left, "day")} to keep it fresh.`,
    },
    demo: {
      summary: "Demo controls (for testing)",
      text: "A case needs revision after 7 days without studying. To check the review flow without waiting, pretend time has passed.",
      none: "Start a case first, then the controls appear here.",
      nine: "Pretend 9 days passed",
      five: "Pretend 5 days passed",
      reset: "Reset to today",
    },
  },

  notebook: {
    label: "Your notes",
    title: "Notebook",
    intro: "Everything you wrote down while studying. You can also add a note here.",
    loading: "Loading your notebook",
    filter: "Filter notes by case",
    all: (n: number) => `All cases (${n})`,
    emptyTitleNone: "Nothing written yet",
    emptyTitleFiltered: "No notes for this case",
    emptyText: "Write a note below, or take notes while you study a clue.",
    openClue: "Open this clue",
    openCase: "Open this case",
    addHeading: "Add a note",
    whichCase: "Which case is it about?",
    toDesk: "Go to the Desk",
    entryLabel: (topic: string, clue: number | null, date: string) =>
      `${topic}${clue ? ` · Clue ${clue}` : ""} · ${date}`,
  },

  notes: {
    newNote: "New note",
    placeholder: "Write what you want to remember...",
    aboutClue: "About which clue?",
    optional: "(optional)",
    wholeCase: "Whole case",
    clueOption: (n: number, title: string) => `Clue ${n}: ${title}`,
    save: "Save note",
    deleteLabel: (snippet: string) => `Delete note: ${snippet}`,
  },

  profile: {
    menuLabel: (name?: string) => (name ? `Profile menu for ${name}` : "Profile menu"),
    guest: "Guest",
    aboutMe: "About me",
    howItWorks: "How CaseFile works",
    myProgress: "My progress",
    reduceMotion: "Reduce motion",
    on: "On",
    off: "Off",
    setUp: "Set up your profile",
    logOut: "Log out",
    logOutTitle: "Log out?",
    logOutText: "Your progress on this device will be cleared.",
    logOutCancel: "Cancel",
    logOutConfirm: "Log out",
  },

  about: {
    title: "About me",
    intro: "This is what you told us when you set up your profile. It is saved on this device only.",
    name: "Name",
    avatar: "Avatar",
    board: "Board",
    grade: "Grade",
    gradeValue: (n: number) => `Grade ${n}`,
    interests: "Interests",
    noInterests: "None chosen",
    level: "Level",
    joined: "Joined",
    notRecorded: "Not recorded",
    noProfileTitle: "No profile yet",
    noProfileText: "Set up a profile to save your progress on this device.",
    toDesk: "Back to the Desk",
    howItWorks: "How CaseFile works",
    loading: "Loading",
  },

  onboarding: {
    eyebrow: "Getting started",
    title: "Set up your profile",
    stepsLabel: "Steps",
    steps: ["About you", "Interests", "Grade", "How it works", "First case"],
    done: "done",
    about: {
      heading: "Tell us about you",
      nameLabel: "Your name",
      nameHelp: "Your first name or a nickname is fine. You do not need to use your full name.",
      nameError: "Add a name so we know what to call you.",
      namePlaceholder: "Sam",
      avatarLegend: "Pick your detective",
      avatarHelp: "Choose the portrait that will stand for you on your profile and the Desk.",
      previewLabel: "Your profile",
      previewEmpty: "Your name here",
    },
    interests: {
      heading: "What are you interested in?",
      text: "Pick as many as you like. We use this to suggest cases you might enjoy.",
      legend: "Your interests",
      none: "Nothing picked yet. You can skip this step.",
      picked: (n: number) => `${n} picked.`,
    },
    grade: {
      heading: "Your board and grade",
      text: "These decide which chapters you see: your board’s chapters, for your grade and the grades below it.",
      legend: "Your grade",
      word: "Grade",
      error: "Pick your grade so we can choose the right level.",
    },
    board: {
      legend: "Your board",
      help: "The exam board your school follows.",
      names: { cbse: "Central Board of Secondary Education", icse: "Indian Certificate of Secondary Education" },
      error: "Pick your board so we can show the right chapters.",
    },
    first: {
      heading: (name: string) => `Welcome, ${name}`,
      sub: "Your profile is ready.",
      caseHeading: "Your first case",
      caseText:
        "We have set up a short practice case. It takes about five minutes and shows you how lessons, evidence, hints and questions work.",
      start: "Start my first case",
      toDesk: "Go to the Desk",
    },
    backHome: "Back to home",
    joinButton: "Next",
    loading: "Loading",
  },

  explainer: {
    title: "How CaseFile works",
    dotsLabel: "Walkthrough progress",
    screen: (n: number, total: number) => `Screen ${n} of ${total}`,
    skip: "Skip",
    back: "Back",
    next: "Next",
    startFirstCase: "Start my first case",
    close: "Close",
    closeDialog: "Close this walkthrough",
    glossaryHeading: "In plain words",
    glossary: [
      { term: "Case", meaning: "subject" },
      { term: "Clue", meaning: "lesson" },
      { term: "Evidence", meaning: "study material" },
      { term: "Interrogation Room", meaning: "quizzes" },
      { term: "Verdict", meaning: "final test" },
      { term: "Cold case", meaning: "revision reminder" },
    ],
    screens: [
      {
        id: "welcome",
        heading: "Learning works like solving a case.",
        body: [
          "Each subject is a case, and you solve it one step at a time.",
          "This is just a way of organising your learning. You do not need to memorise anything.",
          "Each new word is explained as you go.",
        ],
      },
      {
        id: "cases",
        heading: "A case is a subject. A clue is a lesson.",
        body: [
          "A case (a subject) is a folder of short lessons called clues.",
          "You complete the clues in order. The case shows how far along you are.",
        ],
      },
      {
        id: "evidence",
        heading: "Evidence is your study material. Hints are help when you’re stuck.",
        body: [
          "Evidence (study material) includes readings, videos, diagrams and practice sets. You find it in the evidence drawer.",
          "Hints come in three levels, from a small nudge to a full explanation. You can use them any time.",
        ],
      },
      {
        id: "board",
        heading: "Connect ideas and keep your notes.",
        body: [
          "The Evidence Board (a visual map) lets you connect ideas that belong together with red string.",
          "The Notebook (your notes) keeps everything you write in one place.",
        ],
      },
      {
        id: "quiz",
        heading: "Check what you know, and come back to review.",
        body: [
          "The Interrogation Room (the quiz area) asks short questions about each clue. The Verdict (the final test) closes a case when you pass it.",
          "Topics you have not studied for a while appear as revision reminders, so you do not forget them.",
        ],
      },
    ],
    mock: {
      clueDone: "Completed",
      clueOpen: "Up next",
      clueLocked: "Not open yet",
      clueNames: ["How water evaporates", "How clouds form", "How water falls"],
      caseName: "The water cycle",
      progress: "1 of 3 lessons completed",
      evidenceDrawer: "Evidence drawer",
      hintsLabel: "Three levels of hints",
      boardLabel: "Evidence Board",
      notebookLabel: "Notebook",
      quizLabel: "Interrogation Room",
      reviewLabel: "Time to revise",
      verdictLabel: "Verdict",
    },
  },

  landing: {
    headerCta: "Get started",
    headerCtaDesk: "The Desk",
    eyebrow: "A learning platform for ages 11 to 15",
    heading: "Learn by working through cases.",
    text: "CaseFile organises school subjects as cases. Each case is a set of short lessons, study material and quizzes, with a final test at the end.",
    cta: "Get started",
    ctaDesk: "Go to the Desk",
    howLink: "See how it works",
    note: "Made for ages 11 to 15. Setting up takes about a minute.",
    howHeading: "How it works",
    steps: [
      {
        title: "Choose a case",
        text: "Pick a subject, such as the water cycle or fractions. Each subject is a case made of short lessons.",
      },
      {
        title: "Work through the lessons",
        text: "Read, watch and practise. Save useful material to your Evidence Board. Hints are there whenever you need help.",
      },
      {
        title: "Check what you know",
        text: "Answer quiz questions after each lesson. When you have finished them all, take the final test to close the case.",
      },
    ],
    peekHeading: "Some of the cases",
    peekText: "Science, maths, history and geography, for Grades 6 to 10. Here is one chapter from each subject.",
    peekAll: (n: number) => `See all ${n} cases`,
    lessons: (n: number) => plural(n, "lesson"),
    finalHeading: "Ready to start learning?",
    finalText: "Set up your profile and begin with a short practice case.",
    finalCta: "Get started",
    finalCtaDesk: "Back to the Desk",
    footer: "CaseFile. A learning platform for ages 11 to 15.",
    headerCases: "Cases",
    headerVideos: "Videos",
    peekOpen: (title: string) => `Open the case: ${title}`,
    peekCta: "Preview this case",
    trust: {
      heading: "For families and teachers",
      text: "Plain answers about privacy, who writes the lessons, and what they cover.",
      linkAll: "Read more for parents and teachers",
      items: [
        {
          title: "No account or email",
          text: "Setting up asks for a first name or nickname, a portrait, interests, a board and a grade. That is all.",
        },
        {
          title: "Saved on this device",
          text: "A learner’s profile, notes and progress are saved in the browser on their own device. The app does not send them to a server.",
        },
        {
          title: "Who writes the lessons",
          text: "To be confirmed by the CaseFile team.",
          pending: true,
        },
        {
          title: "Which curriculum it follows",
          text: "To be confirmed by the CaseFile team.",
          pending: true,
        },
      ] as { title: string; text: string; pending?: boolean }[],
    },
    footerNav: {
      explore: "Explore",
      subjects: "Subjects",
      cases: "Cases",
      videos: "Videos",
      how: "How it works",
      families: "For families and teachers",
      parents: "Parents and teachers",
      privacy: "Privacy and safety",
      content: "Who creates the content",
      curriculum: "Curriculum",
    },
    home: "Home",
    illustrationLabel:
      "A desk seen from above. On it are a manila case folder labelled The Vanishing Puddle, a magnifying glass, a sticky note, a notebook, a mug, a pencil, and two cards joined by red string.",
  },

  grades: {
    label: (n: number) => `Grade ${n}`,
    filter: "Grade",
    yourGrade: "Your grade",
    note: "Suggested grade level",
    goalsHeading: "What you will learn",
    /** Shown on chapter lists so students know why higher grades are missing */
    showing: (grade: number, board: "cbse" | "icse") => {
      const b = board === "cbse" ? "CBSE" : "ICSE";
      return grade === 6 ? `Showing ${b} Grade 6 chapters, your board and grade.` : `Showing ${b} Grades 6 to ${grade}: your board, your grade and the grades below it.`;
    },
  },

  /** A direct link to a chapter or video above the student's grade */
  locked: {
    meta: "Not open for your grade",
    label: "Restricted file",
    title: "This file is above your grade",
    text: (contentGrade: number | null, studentGrade: number | null) =>
      contentGrade && studentGrade
        ? `This is Grade ${contentGrade} material. Your profile is set to Grade ${studentGrade}, so you can open Grade ${studentGrade === 6 ? "6" : `6 to ${studentGrade}`} chapters and videos.`
        : "This material is not open for the grade on your profile.",
    boardTitle: "This file belongs to another board",
    boardText: (contentBoard: string, studentBoard: string) =>
      `This chapter is written for ${contentBoard}. Your profile is set to ${studentBoard}, so you see the ${studentBoard} chapters instead.`,
    changeGrade: "Picked the wrong grade or board? Log out from the profile menu and set up your profile again.",
    toCases: "Back to your cases",
    toSubjects: "Browse subjects",
  },

  /** Breadcrumbs and "where am I" wording shared by subject, chapter, lesson and video pages */
  wayfinding: {
    breadcrumb: "Breadcrumb",
    subjects: "Subjects",
    videos: "Videos",
    prevChapter: "Previous chapter",
    nextChapter: "Next chapter",
    prevSubject: "Previous subject",
    nextSubject: "Next subject",
    prevLesson: "Previous lesson",
    nextLesson: "Next lesson",
    backToChapter: "Back to the chapter",
    allChapters: (subject: string) => `All ${subject} chapters`,
    youAreHere: "You are here",
    chapterNav: "Chapters in this subject",
    lessonNav: "Lessons in this chapter",
  },

  subjectsPage: {
    label: "Browse",
    title: "Subjects",
    intro: "Each subject is made of chapters. In CaseFile a chapter is a case, and each lesson inside it is a clue.",
    chapters: (n: number) => plural(n, "chapter"),
    lessons: (n: number) => plural(n, "lesson"),
    open: (label: string) => `Open ${label}`,
    chaptersHeading: "Chapters",
    chaptersIntro: "Lessons inside a chapter open one after another. Finish them all to take the chapter’s final test.",
    videosHeading: (label: string) => `${label} videos`,
    seeVideos: "See all videos",
    loading: "Loading chapters",
    notFound: "Subject not found",
    sameAsCases: "Prefer one long list? See every case.",
  },

  videos: {
    label: "Watch and learn",
    title: "Videos",
    intro: "Short videos that go with the lessons. They play right here on CaseFile.",
    filterLabel: "Filter videos",
    subject: "Subject",
    chapter: "Chapter",
    all: "All",
    showing: (n: number) => (n === 1 ? "Showing 1 video" : `Showing ${n} videos`),
    emptyTitle: "No videos here yet",
    emptyText: "The CaseFile team adds videos over time. Try another subject, or work through a case.",
    emptyCta: "Browse the cases",
    clearFilters: "Show all videos",
    errorTitle: "We could not load the videos",
    errorText: "Please try again in a moment.",
    tryAgain: "Try again",
    loading: "Loading videos",
    watch: "Watch",
    openVideo: (title: string) => `Watch: ${title}`,
    noThumb: "Video",
    play: (title: string) => `Play video: ${title}`,
    playNote: "The video loads from its host only after you press Play.",
    playerLabel: (title: string) => `Video player: ${title}`,
    fallbackTitle: "Trouble playing this video?",
    fallbackText: "Some browsers, schools and networks block embedded video.",
    openAt: (host: string) => `Open it on ${host}`,
    directFailed: "This video file could not be played. Check your connection, or try again later.",
    credit: (title: string, channel: string) => `Video: “${title}” by ${channel}, on YouTube.`,
    noteLabel: "Note for teachers and parents:",
    captionsLabel: "Captions:",
    captionsHow: "Turn them on with the CC button in the player.",
    transcript: "Transcript",
    showTranscript: "Show the transcript",
    noTranscript: "No transcript has been added for this video yet.",
    relatedLesson: "Related lesson",
    goToLesson: "Go to the lesson",
    chapterLabel: "Chapter",
    moreInChapter: "More videos in this chapter",
    moreInSubject: (label: string) => `More ${label} videos`,
    backToVideos: "All videos",
    prevVideo: "Previous video",
    nextVideo: "Next video",
    lessonHeading: "Watch and learn",
    lessonIntro: "Videos for this lesson.",
    chapterHeading: "Videos for this chapter",
    notFound: "Video not found",
    hosts: { youtube: "YouTube", vimeo: "Vimeo", file: "the video file" } as Record<string, string>,
  },

  /** The parents and teachers page. Anything marked pending is a placeholder, not a claim. */
  families: {
    eyebrow: "For parents and teachers",
    heading: "What families and teachers should know",
    intro: "CaseFile is a learning platform for ages 11 to 15. This page covers privacy, who writes the lessons, and what they cover. Where we do not yet have a confirmed answer, it says so.",
    pending: "To be confirmed",
    back: "Back to the home page",
    sections: {
      privacy: {
        id: "privacy",
        heading: "Privacy and safety",
        facts: [
          "Setting up a profile asks for a first name or nickname, a portrait, interests, a board (CBSE or ICSE) and a grade (6 to 10). It does not ask for an email address, a surname or a password.",
          "A learner’s profile, notes and progress are saved in the browser on the device they use. Only the grade and board are sent to the server, in cookies, to choose which chapters to show.",
          "Because they are stored in that browser, clearing the browser’s site data removes them, and they do not follow the learner to another device.",
          "There is no chat, messaging or public profile between learners.",
          "Videos play inside CaseFile, but they come from the video’s own host, such as YouTube or Vimeo. Nothing is loaded from that host until a learner presses Play. After that, the host may collect data under its own privacy policy.",
        ],
        pendingNote: "The full privacy policy is at /privacy. A safeguarding contact has not been published yet.",
      },
      content: {
        id: "content",
        heading: "Who creates the content",
        pendingNote: "The author or team behind the lessons, and how they are reviewed, have not been confirmed yet. We will not name anyone here until we can.",
      },
      curriculum: {
        id: "curriculum",
        heading: "Which curriculum it follows",
        facts: (chapters: number, lessons: number, grades: string) => [
          `CaseFile has ${chapters} chapters and ${lessons} lessons across science, maths, history and geography, for ${grades}, plus one short practice case.`,
          "Each chapter has a suggested grade level chosen by the project team. These are suggestions. They are not matched to any official curriculum or exam board.",
        ],
        pendingNote: "Which curriculum or exam board the lessons follow has not been confirmed. CaseFile does not claim any curriculum alignment until it has.",
      },
    },
  },

  notFound: {
    stamp: "Missing",
    title: "We can’t find that page",
    text: "The page you wanted is not here. The address may have a typo, or the case may have moved.",
    toDesk: "Go to the Desk",
    browse: "Browse cases",
  },

  preview: {
    label: "Preview case",
    backToCase: "Back to the case file",
    tryPuddle: "Open the Vanishing Puddle",
    verdictTitle: "The Verdict",
    verdictText: "This case is a preview, so its final test is not written yet.",
    reviewTitle: "Review",
    reviewText: "This case is a preview, so there are no questions to revisit yet.",
    roomTitle: "Interrogation Room",
    roomText: "This case is a preview, so the questions are not written yet.",
  },

  /** Choosing student or teacher on the sign-up page */
  role: {
    legend: "I am a",
    student: "Student",
    teacher: "Teacher",
  },

  /** Teacher sign-up, sign-in and the teacher Desk */
  teach: {
    eyebrow: "For teachers",
    title: "Teacher sign-in",
    intro: "Teachers can browse every chapter for their board and use the Drawer to share files, links, notes and deadlines with a class.",
    tabs: { signUp: "Create an account", signIn: "Sign in" },
    name: "Your name, as students will see it",
    username: "Username",
    usernameHelp: "3 to 30 characters: lower-case letters, numbers, dots, dashes or underscores.",
    password: "Password",
    passwordHelp: "At least 10 characters.",
    board: "Your board",
    create: "Create teacher account",
    signIn: "Sign in",
    working: "Please wait…",
    errors: {
      name: "Enter your name.",
      username: "Choose a username of 3 to 30 characters: lower-case letters, numbers, dots, dashes or underscores.",
      password: "Use a password of at least 10 characters.",
      board: "Choose your board.",
      taken: "That username is already taken. Try another.",
      wrong: "That username and password do not match.",
      "too-many": "Too many attempts. Wait a few minutes and try again.",
      "no-secret": "Teacher accounts are not switched on for this site yet.",
      "no-storage": "Teacher accounts need storage that is not set up on this site yet.",
      network: "Could not reach the server. Check your connection and try again.",
      generic: "Something went wrong. Try again.",
    } as Record<string, string>,
    privacy: "We store your name, username, board, a scrambled (hashed) version of your password, your classes and anything you upload.",
    welcome: (name: string) => `Welcome, ${name}`,
    roleLine: (board: string) => `Teacher · ${board}`,
    signOut: "Sign out",
    menuLabel: (name: string) => `Teacher menu for ${name}`,
    browse: "Browse the library",
    deleteAccount: "Delete my teacher account",
    deleteAccountTitle: "Delete your teacher account?",
    deleteAccountText: "Your account, all your classes and everything in their Drawers, including files, will be deleted for good. Students will no longer see them.",
    deleteAccountConfirm: "Delete account",
  },

  /** The Drawer: teachers share materials with a class; students see them on their Desk */
  drawer: {
    title: "The Drawer",
    teacherIntro: "Make a class, share its code with your students, then put files, links, notes and deadlines in its Drawer.",
    studentIntro: "Files, links and deadlines from your teachers. Ask your teacher for your class code.",
    loading: "Opening the Drawer…",
    error: "The Drawer could not be loaded.",
    retry: "Try again",
    unavailable: "The Drawer is not switched on for this site yet.",
    classes: "Your classes",
    noClasses: "No classes yet. Make one below.",
    pickClass: "Choose a class to open its Drawer.",
    newClass: "Make a class",
    className: "Class name",
    classNamePlaceholder: "For example, 8B Science",
    classGrade: "Grade",
    createClass: "Make class",
    code: "Class code",
    codeHelp: "Students type this on their Desk to join.",
    copyCode: "Copy code",
    copied: "Copied",
    items: (n: number) => (n === 1 ? "1 item" : `${n} items`),
    open: "Open",
    deleteClass: "Delete class",
    deleteClassTitle: "Delete this class?",
    deleteClassText: "Everything in its Drawer, including files, will be deleted. Students will no longer see it.",
    cancel: "Cancel",
    confirmDelete: "Delete",
    addItem: "Add to the Drawer",
    itemTitle: "Title",
    itemTitlePlaceholder: "For example, Chapter 3 worksheet",
    message: "Message (optional)",
    link: "Link (optional)",
    dueDate: "Due date (optional)",
    file: "File (optional)",
    fileHelp: "PDF, PNG, JPG, Word (.docx), PowerPoint (.pptx) or text, up to 4 MB.",
    add: "Add to Drawer",
    added: "Added to the Drawer.",
    empty: "Nothing in this Drawer yet.",
    remove: "Remove",
    due: (date: string) => `Due ${date}`,
    overdue: "Past due",
    dueSoon: "Due soon",
    download: (name: string) => `Open ${name}`,
    visit: "Open link",
    itemErrors: {
      title: "Give the item a title.",
      link: "That link does not look right. It must start with https:// or http://.",
      dueDate: "Choose a valid date.",
      "too-big": "That file is bigger than 4 MB.",
      "bad-type": "That file type is not allowed. Use PDF, PNG, JPG, DOCX, PPTX or TXT.",
      "drawer-full": "This Drawer is full (100 items). Remove some first.",
      generic: "Could not add that. Try again.",
    } as Record<string, string>,
    join: "Join a class",
    joinLabel: "Class code",
    joinPlaceholder: "8 letters and numbers",
    joinButton: "Join",
    joinChecking: "Checking…",
    joinBad: "That code is not 8 letters and numbers.",
    joinNotFound: "No class has that code. Check it with your teacher.",
    joinTooMany: "Too many tries. Wait a few minutes.",
    joined: (name: string) => `You joined ${name}.`,
    leave: "Leave class",
    fromTeacher: (teacher: string, grade: number) => `${teacher} · Grade ${grade}`,
    missingClass: "This class no longer exists.",
    studentEmpty: "Join a class with the code your teacher gives you.",
    noItems: "Your teacher has not added anything yet.",
  },

  /** The privacy policy (/privacy). Each point describes what the code actually does; see the source files named in comments. */
  privacy: {
    meta: "Privacy policy",
    linkLabel: "Read the privacy policy",
    label: "Privacy",
    title: "Privacy policy",
    updated: "Last updated: 4 October 2026",
    intro:
      "CaseFile is a learning website for students aged 11 to 15, with tools for their teachers. This policy explains what information CaseFile keeps, where it is kept, who can see it and how to remove it. We have tried to keep it short and plain.",
    contactPending:
      "The name and contact address of the organisation running this website have not been added yet. Until they are, questions about privacy should go to the school or teacher who asked you to use CaseFile.",
    sections: [
      {
        id: "students",
        heading: "Students",
        points: [
          "To set up a profile, a student gives a first name or nickname, picks a portrait, may pick some interests, and chooses a board (CBSE or ICSE) and a grade (6 to 10). We do not ask students for an email address, a surname, a password, a phone number or a photo.",
          "The profile, progress, notes, evidence board and settings are saved in the browser on the device the student uses (in its local storage). They are not sent to our servers, and they do not follow the student to another device.",
          "Two small cookies hold the student’s grade and board, so the website can show only the chapters for that board and grade. They are sent to our server with each page request for that purpose only.",
          "If a student joins a teacher’s class, the class code is saved on the device and sent to our server to fetch that class’s Drawer. The server does not record which student asked.",
        ],
      },
      {
        id: "teachers",
        heading: "Teachers",
        points: [
          "A teacher account stores the teacher’s name (as students will see it), a username, their board, and a scrambled version of their password (a salted scrypt hash). The password itself is never stored.",
          "We also store the classes a teacher creates (name, grade and a random code) and everything they add to a class Drawer: titles, messages, links, due dates and uploaded files.",
          "Signing in sets a session cookie that keeps the teacher signed in for up to 7 days. It cannot be read by scripts on the page and cannot be changed without our server’s secret key.",
          "Anyone who has a class code can see that class’s Drawer. Teachers should share codes only with their own students, and should not upload personal information about students, such as marks, reports or photos.",
        ],
      },
      {
        id: "cookies",
        heading: "Cookies and similar storage",
        points: [
          "casefile_grade and casefile_board: the grade and board that decide which chapters are shown. They last a year for students (7 days for teachers) and are removed when you log out.",
          "cf_teacher: keeps a teacher signed in, for up to 7 days.",
          "cf_editor: keeps a content editor signed in to the editor desk, for up to 8 hours. Only editors have it.",
          "Local storage in the browser holds the student profile and progress described above.",
          "CaseFile has no advertising, no analytics or tracking scripts, and no social-media buttons. Fonts are served from this website, not from another company.",
        ],
      },
      {
        id: "others",
        heading: "Other companies involved",
        points: [
          "Hosting: the website runs on Vercel. Like any web host, Vercel processes technical information about each request, such as IP addresses, to deliver pages and keep the service secure, under its own privacy policy.",
          "Storage: teacher accounts, classes, Drawer items and uploaded files, and the list of extra lesson videos, are stored in a Redis database provided by Upstash.",
          "Videos: lesson videos come from YouTube. Nothing is loaded from YouTube until someone presses Play. The player uses YouTube’s privacy-enhanced mode (youtube-nocookie.com), but once a video plays, YouTube may collect data under its own privacy policy.",
          "Links in a Drawer may lead to other websites, which have their own privacy policies.",
        ],
      },
      {
        id: "keeping",
        heading: "How long we keep information, and how to remove it",
        points: [
          "Student information stays in the browser until the student logs out from the profile menu (which clears it from that device) or clears the browser’s site data.",
          "Teacher information stays until the teacher removes it. Teachers can remove single Drawer items, delete whole classes, or delete their account from the bottom of their Desk, which removes the account, all its classes, Drawer items and files.",
          "Technical logs kept by the hosting provider are kept for a limited time under the provider’s own policy.",
        ],
      },
      {
        id: "security",
        heading: "Keeping information safe",
        points: [
          "The website is served over HTTPS. Teacher passwords are stored only as salted hashes. Repeated failed sign-in attempts are slowed down.",
          "Uploaded files are checked by type and size (PDF, PNG, JPG, DOCX, PPTX or text, up to 4 MB) and are served in a way that stops them running as part of this website.",
          "No system is perfectly secure. If you think something has gone wrong, tell the school or teacher who asked you to use CaseFile.",
        ],
      },
      {
        id: "children",
        heading: "Children",
        points: [
          "CaseFile is designed for students aged 11 to 15, usually as part of their schoolwork. Because student profiles stay on the student’s own device and contain no contact details, we do not hold personal accounts for students.",
          "Schools and parents can ask a student to log out on a shared device to clear their information from it.",
        ],
      },
      {
        id: "changes",
        heading: "Changes to this policy",
        points: [
          "If what CaseFile keeps or shares changes, this page will be updated and the date at the top will change.",
        ],
      },
    ],
    contactHeading: "Contact",
  },
} as const;
