import type { CaseDef, ClueDef } from "@/lib/types";

/*
  GENERATED by `npm run gen:curriculum` from the chapter files in this folder. Do not edit by hand.
  It holds only the chapter and lesson lists (no lesson text), so browser code can use it without
  downloading every lesson. The lesson text is in specs.ts, which only server code imports.
*/
export const NEW_CASES: CaseDef[] = [
 {
  "id": "maps-globes",
  "number": "058",
  "title": "The Case of the Lost Explorer",
  "topic": "Maps and globes",
  "subject": "geography",
  "grade": 6,
  "tagline": "Learn to read maps, find any place on Earth and measure real distances.",
  "hook": "An explorer has sent a message from somewhere far away, but the only clue is a set of numbers and a torn map. To find them, you will need to read the map's grid, scale and symbols.",
  "goal": "Find places and measure distances using coordinates, scales, grids and map keys.",
  "learn": [
   "Give a place's position using latitude and longitude",
   "Use a scale to turn a distance on a map into a real distance",
   "Find places with compass directions and grid references",
   "Read map symbols and a key",
   "Name the continents and oceans"
  ],
  "clues": [
   {
    "id": "lat-long",
    "title": "Latitude and longitude",
    "goals": [
     "Say what latitude and longitude measure",
     "Name the equator and the prime meridian",
     "Read a pair of coordinates such as 30° N, 31° E"
    ],
    "teaser": "Two numbers can describe any place on Earth.",
    "minutes": 9,
    "evidence": [
     {
      "id": "lat-long-read",
      "kind": "reading",
      "title": "Latitude and longitude",
      "minutes": 4,
      "blurb": "Say what latitude and longitude measure"
     },
     {
      "id": "lat-long-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "lat-long-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "scale",
    "title": "Map scale and distance",
    "goals": [
     "Explain what a map scale shows",
     "Read a ratio scale such as 1:50 000 and a bar scale",
     "Calculate a real distance from a distance on a map"
    ],
    "teaser": "Turn centimetres on a map into kilometres on the ground.",
    "minutes": 9,
    "evidence": [
     {
      "id": "scale-read",
      "kind": "reading",
      "title": "Map scale and distance",
      "minutes": 4,
      "blurb": "Explain what a map scale shows"
     },
     {
      "id": "scale-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "scale-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "directions",
    "title": "Compass directions and grid references",
    "goals": [
     "Name the eight compass directions",
     "Say what a grid reference is",
     "Give a four-figure grid reference"
    ],
    "teaser": "Describe where things are using directions and grid squares.",
    "minutes": 9,
    "evidence": [
     {
      "id": "directions-read",
      "kind": "reading",
      "title": "Compass directions and grid references",
      "minutes": 4,
      "blurb": "Name the eight compass directions"
     },
     {
      "id": "directions-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "directions-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "symbols",
    "title": "Map symbols and keys",
    "goals": [
     "Say what a map key (legend) is for",
     "Recognise common map symbols and colours",
     "Choose the right type of map for a purpose"
    ],
    "teaser": "Learn the picture language that maps use.",
    "minutes": 9,
    "evidence": [
     {
      "id": "symbols-read",
      "kind": "reading",
      "title": "Map symbols and keys",
      "minutes": 4,
      "blurb": "Say what a map key (legend) is for"
     },
     {
      "id": "symbols-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "symbols-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "continents",
    "title": "Continents and oceans",
    "goals": [
     "Name the seven continents",
     "Name the five oceans",
     "Say which are the largest and smallest"
    ],
    "teaser": "Name and place the seven continents and five oceans.",
    "minutes": 9,
    "evidence": [
     {
      "id": "continents-read",
      "kind": "reading",
      "title": "Continents and oceans",
      "minutes": 4,
      "blurb": "Name the seven continents"
     },
     {
      "id": "continents-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "continents-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   }
  ]
 },
 {
  "id": "ratios",
  "number": "071",
  "title": "The Case of the Secret Recipe",
  "topic": "Ratios and percentages",
  "subject": "maths",
  "grade": 7,
  "tagline": "Compare amounts, scale recipes, find the best buy and work with percentages.",
  "hook": "A bakery's cake tastes perfect every single time. The secret is not a rare ingredient. It is the right amounts in the right ratio. To crack the recipe, you will need ratios, rates and percentages.",
  "goal": "Use ratios, rates and percentages to compare amounts and solve everyday problems.",
  "learn": [
   "Say what a ratio compares and write one correctly",
   "Make equivalent ratios and simplify them",
   "Find a unit rate and use it to compare prices and speeds",
   "Say what a percentage means and convert it to a fraction and a decimal",
   "Find a percentage of an amount"
  ],
  "clues": [
   {
    "id": "what-ratio",
    "title": "What a ratio is",
    "goals": [
     "Say what a ratio compares",
     "Write a ratio in the form a:b",
     "Tell the difference between part-to-part and part-to-whole"
    ],
    "teaser": "A ratio compares two amounts, like flour to sugar.",
    "minutes": 9,
    "evidence": [
     {
      "id": "what-ratio-read",
      "kind": "reading",
      "title": "What a ratio is",
      "minutes": 4,
      "blurb": "Say what a ratio compares"
     },
     {
      "id": "what-ratio-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "what-ratio-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "equiv-ratio",
    "title": "Equivalent ratios and simplifying",
    "goals": [
     "Make equivalent ratios by multiplying or dividing both parts by the same number",
     "Simplify a ratio",
     "Use equivalent ratios to scale a recipe"
    ],
    "teaser": "Scale a recipe up or down, or write a ratio in its simplest form.",
    "minutes": 9,
    "evidence": [
     {
      "id": "equiv-ratio-read",
      "kind": "reading",
      "title": "Equivalent ratios and simplifying",
      "minutes": 4,
      "blurb": "Make equivalent ratios by multiplying or dividing both parts by the same number"
     },
     {
      "id": "equiv-ratio-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "equiv-ratio-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "unit-rate",
    "title": "Unit rates",
    "goals": [
     "Say what a rate and a unit rate are",
     "Calculate a unit rate by dividing",
     "Use unit rates to compare prices and speeds"
    ],
    "teaser": "Find the price of one, or the speed per hour, to compare fairly.",
    "minutes": 9,
    "evidence": [
     {
      "id": "unit-rate-read",
      "kind": "reading",
      "title": "Unit rates",
      "minutes": 4,
      "blurb": "Say what a rate and a unit rate are"
     },
     {
      "id": "unit-rate-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "unit-rate-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "percent-basics",
    "title": "What percentages mean",
    "goals": [
     "Say that per cent means out of 100",
     "Convert between fractions, decimals and percentages",
     "Use percentages to compare amounts with different totals"
    ],
    "teaser": "Per cent means out of 100, which makes fair comparisons easy.",
    "minutes": 9,
    "evidence": [
     {
      "id": "percent-basics-read",
      "kind": "reading",
      "title": "What percentages mean",
      "minutes": 4,
      "blurb": "Say that per cent means out of 100"
     },
     {
      "id": "percent-basics-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "percent-basics-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "percent-of",
    "title": "Percentage of an amount",
    "goals": [
     "Find a percentage of an amount",
     "Use 10% and 1% as building blocks",
     "Work out a discount or an increase"
    ],
    "teaser": "Work out discounts, increases and shares in your head.",
    "minutes": 9,
    "evidence": [
     {
      "id": "percent-of-read",
      "kind": "reading",
      "title": "Percentage of an amount",
      "minutes": 4,
      "blurb": "Find a percentage of an amount"
     },
     {
      "id": "percent-of-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "percent-of-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   }
  ]
 },
 {
  "id": "ancient-greece",
  "number": "083",
  "title": "The Case of the Painted Vase",
  "topic": "Ancient Greece",
  "subject": "history",
  "grade": 7,
  "tagline": "Explore Greek city-states, democracy, Sparta, the Persian Wars and Alexander the Great.",
  "hook": "A museum has found a painted vase. It shows soldiers marching, athletes running and a crowd of men voting. It comes from ancient Greece, but which part of it, and what is it showing? To read the vase, you need to know how the Greeks lived, ruled and fought.",
  "goal": "Describe how ancient Greek city-states were organised, how they fought the Persians, and how Alexander spread Greek culture.",
  "learn": [
   "Explain why Greece was made up of many city-states",
   "Describe how democracy worked in Athens, and who was left out",
   "Compare Athens and Sparta",
   "Say how the Greeks defeated the Persian invasions",
   "Describe Alexander the Great's conquests and their effects"
  ],
  "clues": [
   {
    "id": "city-states",
    "title": "Greek city-states",
    "goals": [
     "Explain why Greece was divided into city-states",
     "Describe the main parts of a polis",
     "Name things that all Greeks shared"
    ],
    "teaser": "Greece was never one country. It was hundreds of small states.",
    "minutes": 9,
    "evidence": [
     {
      "id": "city-states-read",
      "kind": "reading",
      "title": "Greek city-states",
      "minutes": 4,
      "blurb": "Explain why Greece was divided into city-states"
     },
     {
      "id": "city-states-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "city-states-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "democracy",
    "title": "Athens and democracy",
    "goals": [
     "Say what democracy means",
     "Describe how the Athenian Assembly made decisions",
     "Explain who was and was not included"
    ],
    "teaser": "The Athenians let citizens vote, but not everyone counted as a citizen.",
    "minutes": 9,
    "evidence": [
     {
      "id": "democracy-read",
      "kind": "reading",
      "title": "Athens and democracy",
      "minutes": 4,
      "blurb": "Say what democracy means"
     },
     {
      "id": "democracy-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "democracy-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "sparta",
    "title": "Sparta",
    "goals": [
     "Describe the main groups in Spartan society",
     "Explain the agoge, the Spartan training system",
     "Compare Sparta and Athens"
    ],
    "teaser": "A city-state built around its army, and the people who paid for it.",
    "minutes": 9,
    "evidence": [
     {
      "id": "sparta-read",
      "kind": "reading",
      "title": "Sparta",
      "minutes": 4,
      "blurb": "Describe the main groups in Spartan society"
     },
     {
      "id": "sparta-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "sparta-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "persian-wars",
    "title": "The Persian Wars",
    "goals": [
     "Describe the main events of the Persian Wars",
     "Explain why the Greeks cooperated",
     "Say what changed in Greece afterwards"
    ],
    "teaser": "Divided Greek states stood together against the biggest empire on Earth.",
    "minutes": 9,
    "evidence": [
     {
      "id": "persian-wars-read",
      "kind": "reading",
      "title": "The Persian Wars",
      "minutes": 4,
      "blurb": "Describe the main events of the Persian Wars"
     },
     {
      "id": "persian-wars-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "persian-wars-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "alexander",
    "title": "Alexander the Great",
    "goals": [
     "Describe Alexander's main conquests",
     "Explain what “Hellenistic” means",
     "Weigh evidence for and against calling him great"
    ],
    "teaser": "A young king who conquered an empire, and the Greek world it created.",
    "minutes": 9,
    "evidence": [
     {
      "id": "alexander-read",
      "kind": "reading",
      "title": "Alexander the Great",
      "minutes": 4,
      "blurb": "Describe Alexander's main conquests"
     },
     {
      "id": "alexander-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "alexander-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   }
  ]
 },
 {
  "id": "matter-atoms",
  "number": "096",
  "title": "The Case of the Invisible Building Blocks",
  "topic": "Matter and atoms",
  "subject": "science",
  "grade": 8,
  "tagline": "Discover what everything is made of, from particles and atoms to compounds and chemical change.",
  "hook": "A chemist drops a pinch of powder into a glass and it vanishes. A moment later, the water fizzes and turns blue. Nothing visible changed the powder, so what really happened? To solve it, you will need to think about the particles you cannot see.",
  "goal": "Explain how matter is built from particles and atoms, how elements and compounds differ, and how chemical changes work.",
  "learn": [
   "Use the particle model to explain solids, liquids and gases",
   "Describe the structure of an atom",
   "Use the periodic table to find and group elements",
   "Tell elements, compounds and mixtures apart",
   "Tell physical changes from chemical changes"
  ],
  "clues": [
   {
    "id": "states",
    "title": "States of matter",
    "goals": [
     "Describe solids, liquids and gases using the particle model",
     "Name the changes of state",
     "Explain what heating does to particles"
    ],
    "teaser": "Solids, liquids and gases are the same particles arranged differently.",
    "minutes": 9,
    "evidence": [
     {
      "id": "states-read",
      "kind": "reading",
      "title": "States of matter",
      "minutes": 4,
      "blurb": "Describe solids, liquids and gases using the particle model"
     },
     {
      "id": "states-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "states-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "atoms",
    "title": "Inside the atom",
    "goals": [
     "Name the three particles in an atom and their charges",
     "Say what the atomic number and mass number tell you",
     "Explain why atoms are neutral"
    ],
    "teaser": "Protons, neutrons and electrons: what atoms are made of.",
    "minutes": 9,
    "evidence": [
     {
      "id": "atoms-read",
      "kind": "reading",
      "title": "Inside the atom",
      "minutes": 4,
      "blurb": "Name the three particles in an atom and their charges"
     },
     {
      "id": "atoms-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "atoms-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "elements",
    "title": "Elements and the periodic table",
    "goals": [
     "Say what an element is",
     "Read symbols and find groups and periods in the periodic table",
     "Describe how Mendeleev's table predicted new elements"
    ],
    "teaser": "One chart that organises every known element.",
    "minutes": 9,
    "evidence": [
     {
      "id": "elements-read",
      "kind": "reading",
      "title": "Elements and the periodic table",
      "minutes": 4,
      "blurb": "Say what an element is"
     },
     {
      "id": "elements-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "elements-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "compounds",
    "title": "Compounds and mixtures",
    "goals": [
     "Say what a compound is",
     "Say what a mixture is",
     "Choose a method to separate a mixture"
    ],
    "teaser": "Atoms joined together, or just mixed together?",
    "minutes": 9,
    "evidence": [
     {
      "id": "compounds-read",
      "kind": "reading",
      "title": "Compounds and mixtures",
      "minutes": 4,
      "blurb": "Say what a compound is"
     },
     {
      "id": "compounds-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "compounds-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "reactions",
    "title": "Chemical and physical changes",
    "goals": [
     "Tell physical changes from chemical changes",
     "Name signs that a chemical reaction has happened",
     "Say what happens to mass in a reaction"
    ],
    "teaser": "Spotting when a new substance has been made.",
    "minutes": 9,
    "evidence": [
     {
      "id": "reactions-read",
      "kind": "reading",
      "title": "Chemical and physical changes",
      "minutes": 4,
      "blurb": "Tell physical changes from chemical changes"
     },
     {
      "id": "reactions-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "reactions-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   }
  ]
 },
 {
  "id": "equations-graphs",
  "number": "105",
  "title": "The Case of the Missing Number",
  "topic": "Equations and graphs",
  "subject": "maths",
  "grade": 8,
  "tagline": "Use letters for unknown numbers, solve equations and draw straight-line graphs.",
  "hook": "A note on the detective's desk says: “I am thinking of a number. Multiply it by 3, then add 4. The answer is 19.” There is no name on the note, only a number to find. To crack it, you will need algebra: letters, equations and graphs.",
  "goal": "Write and solve simple equations, and draw and describe straight-line graphs.",
  "learn": [
   "Use a letter for an unknown number and write expressions",
   "Solve one-step and two-step equations",
   "Plot points and draw a line from a rule",
   "Find the slope of a line",
   "Use the equation y = mx + b"
  ],
  "clues": [
   {
    "id": "expressions",
    "title": "Variables and expressions",
    "goals": [
     "Say what a variable and an expression are",
     "Write an expression from a description in words",
     "Evaluate an expression by substituting a number"
    ],
    "teaser": "A letter can stand for any number. That is the heart of algebra.",
    "minutes": 9,
    "evidence": [
     {
      "id": "expressions-read",
      "kind": "reading",
      "title": "Variables and expressions",
      "minutes": 4,
      "blurb": "Say what a variable and an expression are"
     },
     {
      "id": "expressions-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "expressions-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "solve",
    "title": "Solving equations",
    "goals": [
     "Say what an equation is",
     "Solve one-step and two-step equations using inverse operations",
     "Check an answer by substituting"
    ],
    "teaser": "Keep both sides balanced to find the missing number.",
    "minutes": 9,
    "evidence": [
     {
      "id": "solve-read",
      "kind": "reading",
      "title": "Solving equations",
      "minutes": 4,
      "blurb": "Say what an equation is"
     },
     {
      "id": "solve-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "solve-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "graphing",
    "title": "Graphing on the coordinate plane",
    "goals": [
     "Plot and read points on the coordinate plane",
     "Make a table of values for a rule",
     "Draw a straight line from a table of values"
    ],
    "teaser": "Turn a rule into a picture of points and a line.",
    "minutes": 9,
    "evidence": [
     {
      "id": "graphing-read",
      "kind": "reading",
      "title": "Graphing on the coordinate plane",
      "minutes": 4,
      "blurb": "Plot and read points on the coordinate plane"
     },
     {
      "id": "graphing-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "graphing-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "slope",
    "title": "Slope and gradient",
    "goals": [
     "Say what slope measures",
     "Calculate slope from two points as rise over run",
     "Tell what positive, negative and zero slopes look like"
    ],
    "teaser": "One number that tells you how steep a line is.",
    "minutes": 9,
    "evidence": [
     {
      "id": "slope-read",
      "kind": "reading",
      "title": "Slope and gradient",
      "minutes": 4,
      "blurb": "Say what slope measures"
     },
     {
      "id": "slope-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "slope-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "slope-intercept",
    "title": "The equation y = mx + b",
    "goals": [
     "Say what m and b mean in y = mx + b",
     "Draw a line from its equation",
     "Write the equation of a line from its slope and y-intercept"
    ],
    "teaser": "Read the slope and starting point straight from the equation.",
    "minutes": 9,
    "evidence": [
     {
      "id": "slope-intercept-read",
      "kind": "reading",
      "title": "The equation y = mx + b",
      "minutes": 4,
      "blurb": "Say what m and b mean in y = mx + b"
     },
     {
      "id": "slope-intercept-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "slope-intercept-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   }
  ]
 },
 {
  "id": "roman-empire",
  "number": "112",
  "title": "The Case of the Buried Road",
  "topic": "The Roman Empire",
  "subject": "history",
  "grade": 8,
  "tagline": "From a small town to a Mediterranean empire, and why it fell.",
  "hook": "Builders digging in a field strike a perfectly straight stone road, laid in careful layers, running towards the horizon. It has been buried for about 1,600 years. Whoever built it planned for a very long time. To find out who, you will have to follow the road back to Rome.",
  "goal": "Describe how Rome grew, how the Republic became an empire, how Romans lived and built, and why the western empire fell.",
  "learn": [
   "Explain how Rome grew from a city to a Mediterranean power",
   "Describe why the Roman Republic ended",
   "Explain how Roman roads, aqueducts and buildings were made",
   "Describe daily life for different groups of people in Rome",
   "Discuss the causes of the fall of the Western Roman Empire"
  ],
  "clues": [
   {
    "id": "rise",
    "title": "The rise of Rome",
    "goals": [
     "Describe how Rome changed from a monarchy to a republic",
     "Explain how the Republic was governed",
     "Say how the Punic Wars made Rome a great power"
    ],
    "teaser": "How a town on the Tiber grew into a Mediterranean power.",
    "minutes": 9,
    "evidence": [
     {
      "id": "rise-read",
      "kind": "reading",
      "title": "The rise of Rome",
      "minutes": 4,
      "blurb": "Describe how Rome changed from a monarchy to a republic"
     },
     {
      "id": "rise-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "rise-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "caesar",
    "title": "Julius Caesar and the end of the Republic",
    "goals": [
     "Describe the main events in Julius Caesar's career",
     "Explain why Caesar was assassinated",
     "Say how Augustus became the first emperor"
    ],
    "teaser": "How ambitious generals and civil war ended 500 years of republic.",
    "minutes": 9,
    "evidence": [
     {
      "id": "caesar-read",
      "kind": "reading",
      "title": "Julius Caesar and the end of the Republic",
      "minutes": 4,
      "blurb": "Describe the main events in Julius Caesar's career"
     },
     {
      "id": "caesar-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "caesar-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "army-roads",
    "title": "The army, roads and engineering",
    "goals": [
     "Describe the Roman legion and what it did",
     "Explain how Roman roads and aqueducts were built",
     "Say why Roman concrete lasted"
    ],
    "teaser": "Legions, straight roads, arches and concrete.",
    "minutes": 9,
    "evidence": [
     {
      "id": "army-roads-read",
      "kind": "reading",
      "title": "The army, roads and engineering",
      "minutes": 4,
      "blurb": "Describe the Roman legion and what it did"
     },
     {
      "id": "army-roads-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "army-roads-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "daily-life",
    "title": "Daily life in Rome",
    "goals": [
     "Describe the main groups in Roman society",
     "Compare homes and daily life for rich and poor Romans",
     "Explain what the Colosseum and baths were for"
    ],
    "teaser": "Homes, baths, games and the lives of different people.",
    "minutes": 9,
    "evidence": [
     {
      "id": "daily-life-read",
      "kind": "reading",
      "title": "Daily life in Rome",
      "minutes": 4,
      "blurb": "Describe the main groups in Roman society"
     },
     {
      "id": "daily-life-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "daily-life-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "fall",
    "title": "Why the Western Empire fell",
    "goals": [
     "Say when and how the Western Empire is said to have ended",
     "Describe several causes of its decline",
     "Explain what continued after the fall"
    ],
    "teaser": "Several linked problems, and a date that marks a long decline.",
    "minutes": 9,
    "evidence": [
     {
      "id": "fall-read",
      "kind": "reading",
      "title": "Why the Western Empire fell",
      "minutes": 4,
      "blurb": "Say when and how the Western Empire is said to have ended"
     },
     {
      "id": "fall-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "fall-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   }
  ]
 },
 {
  "id": "weather-climate",
  "number": "119",
  "title": "The Case of the Strange Season",
  "topic": "Weather and climate",
  "subject": "geography",
  "grade": 8,
  "tagline": "Tell weather from climate, and find out what shapes the air, the wind and the living world.",
  "hook": "One January it is freezing. A week later, the sun shines and people sit outside in T-shirts. A neighbour says, “The climate must be changing!” Is that right? To decide, you need to understand weather, climate, wind and the habitats they create.",
  "goal": "Explain the difference between weather and climate, and describe what shapes climate zones, winds, fronts and biomes.",
  "learn": [
   "Tell weather from climate and name instruments that measure weather",
   "Describe the world's main climate zones and what affects them",
   "Explain how air pressure causes wind",
   "Read the basics of a weather map and a forecast",
   "Describe the main biomes and how living things are adapted to them"
  ],
  "clues": [
   {
    "id": "weather-v-climate",
    "title": "Weather or climate?",
    "goals": [
     "Say how weather and climate differ",
     "Name instruments that measure the weather",
     "Read a simple climate graph"
    ],
    "teaser": "What is happening today, and what usually happens over many years.",
    "minutes": 9,
    "evidence": [
     {
      "id": "weather-v-climate-read",
      "kind": "reading",
      "title": "Weather or climate?",
      "minutes": 4,
      "blurb": "Say how weather and climate differ"
     },
     {
      "id": "weather-v-climate-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "weather-v-climate-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "climate-zones",
    "title": "Climate zones",
    "goals": [
     "Name the three broad climate zones and where they lie",
     "Explain why latitude affects climate",
     "Describe other factors such as altitude, the sea and ocean currents"
    ],
    "teaser": "Why the Sahara, London and Antarctica are so different.",
    "minutes": 9,
    "evidence": [
     {
      "id": "climate-zones-read",
      "kind": "reading",
      "title": "Climate zones",
      "minutes": 4,
      "blurb": "Name the three broad climate zones and where they lie"
     },
     {
      "id": "climate-zones-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "climate-zones-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "wind-pressure",
    "title": "Air pressure and wind",
    "goals": [
     "Say what air pressure is",
     "Explain why warm air rising creates low pressure",
     "Describe how wind blows between high and low pressure, and explain a sea breeze"
    ],
    "teaser": "Wind is air moving from high pressure to low pressure.",
    "minutes": 9,
    "evidence": [
     {
      "id": "wind-pressure-read",
      "kind": "reading",
      "title": "Air pressure and wind",
      "minutes": 4,
      "blurb": "Say what air pressure is"
     },
     {
      "id": "wind-pressure-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "wind-pressure-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "fronts-forecast",
    "title": "Fronts and forecasting",
    "goals": [
     "Say what a front is",
     "Describe the weather brought by warm and cold fronts",
     "Explain how forecasts are made and why they can be wrong"
    ],
    "teaser": "Where warm and cold air meet, and how forecasters look ahead.",
    "minutes": 9,
    "evidence": [
     {
      "id": "fronts-forecast-read",
      "kind": "reading",
      "title": "Fronts and forecasting",
      "minutes": 4,
      "blurb": "Say what a front is"
     },
     {
      "id": "fronts-forecast-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "fronts-forecast-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "biomes",
    "title": "Biomes",
    "goals": [
     "Say what a biome is",
     "Describe the main land biomes and their climates",
     "Give examples of how living things are adapted to their biome"
    ],
    "teaser": "Climate shapes the plants and animals that can live somewhere.",
    "minutes": 9,
    "evidence": [
     {
      "id": "biomes-read",
      "kind": "reading",
      "title": "Biomes",
      "minutes": 4,
      "blurb": "Say what a biome is"
     },
     {
      "id": "biomes-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "biomes-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   }
  ]
 },
 {
  "id": "forces-motion",
  "number": "127",
  "title": "The Case of the Runaway Trolley",
  "topic": "Forces and motion",
  "subject": "science",
  "grade": 9,
  "tagline": "Measure motion and use Newton's three laws to explain why things speed up, slow down or stay still.",
  "hook": "A trolley is found at the bottom of a hill, with a dent in a wall. Nobody saw it roll. Was it pushed? Did it roll on its own? To work out what happened, you will need to measure its motion and understand the forces on it.",
  "goal": "Describe motion with speed, velocity and acceleration, and explain it using Newton's laws of motion.",
  "learn": [
   "Calculate speed and acceleration",
   "Explain Newton's first law and inertia",
   "Use F = ma to relate force, mass and acceleration",
   "Explain action and reaction forces",
   "Tell mass from weight"
  ],
  "clues": [
   {
    "id": "speed-accel",
    "title": "Speed, velocity and acceleration",
    "goals": [
     "Calculate speed from distance and time",
     "Say how velocity differs from speed",
     "Calculate acceleration from a change in velocity"
    ],
    "teaser": "Three ways to describe how something moves.",
    "minutes": 9,
    "evidence": [
     {
      "id": "speed-accel-read",
      "kind": "reading",
      "title": "Speed, velocity and acceleration",
      "minutes": 4,
      "blurb": "Calculate speed from distance and time"
     },
     {
      "id": "speed-accel-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "speed-accel-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "newton1",
    "title": "Newton's first law",
    "goals": [
     "State Newton's first law",
     "Explain inertia",
     "Use the first law to explain everyday events"
    ],
    "teaser": "Objects keep doing what they are doing, until a force acts.",
    "minutes": 9,
    "evidence": [
     {
      "id": "newton1-read",
      "kind": "reading",
      "title": "Newton's first law",
      "minutes": 4,
      "blurb": "State Newton's first law"
     },
     {
      "id": "newton1-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "newton1-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "newton2",
    "title": "Newton's second law",
    "goals": [
     "State Newton's second law as F = ma",
     "Calculate force, mass or acceleration",
     "Explain how mass affects acceleration"
    ],
    "teaser": "Force equals mass times acceleration.",
    "minutes": 9,
    "evidence": [
     {
      "id": "newton2-read",
      "kind": "reading",
      "title": "Newton's second law",
      "minutes": 4,
      "blurb": "State Newton's second law as F = ma"
     },
     {
      "id": "newton2-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "newton2-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "newton3",
    "title": "Newton's third law",
    "goals": [
     "State Newton's third law",
     "Identify an action-reaction pair",
     "Explain why the two forces do not cancel out"
    ],
    "teaser": "Every force has an equal and opposite partner.",
    "minutes": 9,
    "evidence": [
     {
      "id": "newton3-read",
      "kind": "reading",
      "title": "Newton's third law",
      "minutes": 4,
      "blurb": "State Newton's third law"
     },
     {
      "id": "newton3-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "newton3-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "gravity-weight",
    "title": "Gravity, mass and weight",
    "goals": [
     "Say what mass and weight are, and their units",
     "Calculate weight using W = m × g",
     "Explain why weight changes with gravity but mass does not"
    ],
    "teaser": "Mass stays the same. Weight depends on where you are.",
    "minutes": 9,
    "evidence": [
     {
      "id": "gravity-weight-read",
      "kind": "reading",
      "title": "Gravity, mass and weight",
      "minutes": 4,
      "blurb": "Say what mass and weight are, and their units"
     },
     {
      "id": "gravity-weight-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "gravity-weight-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   }
  ]
 },
 {
  "id": "geometry",
  "number": "134",
  "title": "The Case of the Crooked Ladder",
  "topic": "Geometry and measurement",
  "subject": "maths",
  "grade": 9,
  "tagline": "Work out angles, lengths, areas and volumes without measuring, using rules that always hold.",
  "hook": "A ladder leans against the wall of a museum, a little too close to a window that was left open. How high does it reach? How far is the foot from the wall? Nobody has a tape measure, but you have some geometry.",
  "goal": "Use geometry rules to find missing angles, lengths, areas and volumes.",
  "learn": [
   "Find missing angles in triangles, polygons and parallel lines",
   "Calculate the circumference and area of a circle",
   "Use the Pythagorean theorem to find missing lengths",
   "Calculate the volume of prisms and cylinders",
   "Use scale factors with similar shapes"
  ],
  "clues": [
   {
    "id": "angles",
    "title": "Angles in triangles and polygons",
    "goals": [
     "Use the angle rules for straight lines, points and parallel lines",
     "Use the angle sum of a triangle",
     "Find the angle sum of any polygon"
    ],
    "teaser": "Find missing angles without a protractor.",
    "minutes": 9,
    "evidence": [
     {
      "id": "angles-read",
      "kind": "reading",
      "title": "Angles in triangles and polygons",
      "minutes": 4,
      "blurb": "Use the angle rules for straight lines, points and parallel lines"
     },
     {
      "id": "angles-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "angles-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "circles",
    "title": "Circles: circumference and area",
    "goals": [
     "Name the parts of a circle",
     "Calculate circumference using C = πd or 2πr",
     "Calculate area using A = πr²"
    ],
    "teaser": "How far round, and how much inside, a circle.",
    "minutes": 9,
    "evidence": [
     {
      "id": "circles-read",
      "kind": "reading",
      "title": "Circles: circumference and area",
      "minutes": 4,
      "blurb": "Name the parts of a circle"
     },
     {
      "id": "circles-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "circles-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "pythagoras",
    "title": "The Pythagorean theorem",
    "goals": [
     "State the Pythagorean theorem",
     "Find a missing side of a right triangle",
     "Use the theorem to test for a right angle"
    ],
    "teaser": "The rule that links the three sides of every right triangle.",
    "minutes": 9,
    "evidence": [
     {
      "id": "pythagoras-read",
      "kind": "reading",
      "title": "The Pythagorean theorem",
      "minutes": 4,
      "blurb": "State the Pythagorean theorem"
     },
     {
      "id": "pythagoras-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "pythagoras-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "volume",
    "title": "Volume of prisms and cylinders",
    "goals": [
     "Say what volume measures and its units",
     "Find the volume of a prism as base area × height",
     "Calculate the volume of a cylinder"
    ],
    "teaser": "How much a 3D shape can hold.",
    "minutes": 9,
    "evidence": [
     {
      "id": "volume-read",
      "kind": "reading",
      "title": "Volume of prisms and cylinders",
      "minutes": 4,
      "blurb": "Say what volume measures and its units"
     },
     {
      "id": "volume-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "volume-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "similar",
    "title": "Similar shapes and scale factor",
    "goals": [
     "Say what similar shapes are",
     "Use a scale factor to find missing lengths",
     "Say how areas and volumes change with the scale factor"
    ],
    "teaser": "Same shape, different size.",
    "minutes": 9,
    "evidence": [
     {
      "id": "similar-read",
      "kind": "reading",
      "title": "Similar shapes and scale factor",
      "minutes": 4,
      "blurb": "Say what similar shapes are"
     },
     {
      "id": "similar-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "similar-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   }
  ]
 },
 {
  "id": "industrial-revolution",
  "number": "141",
  "title": "The Case of the Silent Mill",
  "topic": "The Industrial Revolution",
  "subject": "history",
  "grade": 9,
  "tagline": "How machines, steam and railways changed how people worked, lived and travelled.",
  "hook": "A mill in the north of England has stood silent for decades. Inside, rusting looms and a boiler room still stand. Whoever worked here lived a life very different from a farmer's a century earlier. To understand what happened, you must go back to before the machines.",
  "goal": "Explain why the Industrial Revolution began in Britain, how it changed work, travel and everyday life, and what it left behind.",
  "learn": [
   "Describe life and work before factories",
   "Explain how steam power and new machines created the factory system",
   "Describe how canals and railways changed transport",
   "Describe conditions in factory towns and the reforms that followed",
   "Weigh the lasting good and harm of industrialisation"
  ],
  "clues": [
   {
    "id": "before",
    "title": "Life before the factories",
    "goals": [
     "Describe the domestic (cottage) system of making goods",
     "Explain how farming changes helped industry grow",
     "List advantages Britain had"
    ],
    "teaser": "Farms, cottages and the changes that made a revolution possible.",
    "minutes": 9,
    "evidence": [
     {
      "id": "before-read",
      "kind": "reading",
      "title": "Life before the factories",
      "minutes": 4,
      "blurb": "Describe the domestic (cottage) system of making goods"
     },
     {
      "id": "before-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "before-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "steam-factories",
    "title": "Steam power and factories",
    "goals": [
     "Name important textile machines and steam inventions",
     "Explain the factory system",
     "Say why factories could be built away from rivers"
    ],
    "teaser": "Machines, coal and steam move work out of the home.",
    "minutes": 9,
    "evidence": [
     {
      "id": "steam-factories-read",
      "kind": "reading",
      "title": "Steam power and factories",
      "minutes": 4,
      "blurb": "Name important textile machines and steam inventions"
     },
     {
      "id": "steam-factories-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "steam-factories-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "inventions-transport",
    "title": "Inventions, canals and railways",
    "goals": [
     "Describe how canals and railways were built and used",
     "Name a key railway milestone",
     "Explain how railways changed daily life"
    ],
    "teaser": "How faster transport changed trade, travel and time itself.",
    "minutes": 9,
    "evidence": [
     {
      "id": "inventions-transport-read",
      "kind": "reading",
      "title": "Inventions, canals and railways",
      "minutes": 4,
      "blurb": "Describe how canals and railways were built and used"
     },
     {
      "id": "inventions-transport-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "inventions-transport-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "factory-life",
    "title": "Life in factory towns",
    "goals": [
     "Describe working conditions in factories and mines",
     "Describe living conditions in industrial towns",
     "Name some reforms and reformers"
    ],
    "teaser": "Long hours, crowded housing, and the reformers who campaigned for change.",
    "minutes": 9,
    "evidence": [
     {
      "id": "factory-life-read",
      "kind": "reading",
      "title": "Life in factory towns",
      "minutes": 4,
      "blurb": "Describe working conditions in factories and mines"
     },
     {
      "id": "factory-life-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "factory-life-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "legacy",
    "title": "Reform and the legacy of industry",
    "goals": [
     "Describe the long-term effects of industrialisation on cities and living standards",
     "Describe the reforms that improved public life",
     "Explain some costs of industrialisation"
    ],
    "teaser": "How industrialisation changed the world, for better and for worse.",
    "minutes": 9,
    "evidence": [
     {
      "id": "legacy-read",
      "kind": "reading",
      "title": "Reform and the legacy of industry",
      "minutes": 4,
      "blurb": "Describe the long-term effects of industrialisation on cities and living standards"
     },
     {
      "id": "legacy-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "legacy-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   }
  ]
 },
 {
  "id": "population-cities",
  "number": "148",
  "title": "The Case of the Crowded City",
  "topic": "Population and cities",
  "subject": "geography",
  "grade": 9,
  "tagline": "Why the world's population grew, why people move, and how cities can cope.",
  "hook": "A small town has just been named one of the fastest-growing places in the country. Schools are full, buses are packed, and new apartment blocks appear every month. Where are all these people coming from? To find out, you need to understand population, migration and cities.",
  "goal": "Explain how and why populations change, why people migrate, and how cities can grow sustainably.",
  "learn": [
   "Explain why the world's population grew so fast and is now slowing",
   "Read and use population pyramids",
   "Explain why people migrate using push and pull factors",
   "Describe urbanisation and the challenges of megacities",
   "Describe ways to make cities sustainable"
  ],
  "clues": [
   {
    "id": "pop-growth",
    "title": "Why the population is growing",
    "goals": [
     "Define birth rate, death rate and natural increase",
     "Explain the demographic transition",
     "Say why growth is slowing"
    ],
    "teaser": "From one billion to eight billion in about two centuries.",
    "minutes": 9,
    "evidence": [
     {
      "id": "pop-growth-read",
      "kind": "reading",
      "title": "Why the population is growing",
      "minutes": 4,
      "blurb": "Define birth rate, death rate and natural increase"
     },
     {
      "id": "pop-growth-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "pop-growth-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "pyramids",
    "title": "Reading population pyramids",
    "goals": [
     "Describe how a population pyramid is drawn",
     "Tell apart expanding, stable and ageing pyramids",
     "Explain what the dependency ratio shows"
    ],
    "teaser": "A graph that shows a country's past and hints at its future.",
    "minutes": 9,
    "evidence": [
     {
      "id": "pyramids-read",
      "kind": "reading",
      "title": "Reading population pyramids",
      "minutes": 4,
      "blurb": "Describe how a population pyramid is drawn"
     },
     {
      "id": "pyramids-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "pyramids-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "migration",
    "title": "Migration: why people move",
    "goals": [
     "Say what migration is and name its types",
     "Explain push and pull factors",
     "Describe effects of migration on origin and destination"
    ],
    "teaser": "Push factors, pull factors and the choices behind them.",
    "minutes": 9,
    "evidence": [
     {
      "id": "migration-read",
      "kind": "reading",
      "title": "Migration: why people move",
      "minutes": 4,
      "blurb": "Say what migration is and name its types"
     },
     {
      "id": "migration-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "migration-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "urbanisation",
    "title": "Urbanisation and megacities",
    "goals": [
     "Define urbanisation and megacity",
     "Explain why cities grow",
     "Describe the problems and opportunities of rapid urban growth"
    ],
    "teaser": "More than half of us now live in towns and cities.",
    "minutes": 9,
    "evidence": [
     {
      "id": "urbanisation-read",
      "kind": "reading",
      "title": "Urbanisation and megacities",
      "minutes": 4,
      "blurb": "Define urbanisation and megacity"
     },
     {
      "id": "urbanisation-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "urbanisation-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "sustainable-cities",
    "title": "Sustainable cities",
    "goals": [
     "Say what a sustainable city is",
     "Describe ways cities reduce harm and improve life",
     "Give examples of cities that have tried"
    ],
    "teaser": "Cities that work for people today and in the future.",
    "minutes": 9,
    "evidence": [
     {
      "id": "sustainable-cities-read",
      "kind": "reading",
      "title": "Sustainable cities",
      "minutes": 4,
      "blurb": "Say what a sustainable city is"
     },
     {
      "id": "sustainable-cities-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "sustainable-cities-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   }
  ]
 },
 {
  "id": "genes-evolution",
  "number": "156",
  "title": "The Case of the Family Resemblance",
  "topic": "Genes and evolution",
  "subject": "science",
  "grade": 10,
  "tagline": "How DNA passes traits from parents to children, and how populations change over time.",
  "hook": "Three generations of one family stand in a photograph. They share the same nose, the same laugh, even the same freckle. But the youngest has a trait no one else has. Where did it come from? To crack it, you will need to read the code hidden in every cell.",
  "goal": "Explain how DNA carries information, how traits are inherited, and how natural selection leads to evolution.",
  "learn": [
   "Describe the structure of DNA and what genes do",
   "Explain dominant and recessive alleles",
   "Use Punnett squares to predict inheritance",
   "Explain how natural selection works",
   "Describe the evidence for evolution"
  ],
  "clues": [
   {
    "id": "dna",
    "title": "DNA and genes",
    "goals": [
     "Describe the structure of DNA",
     "Say what a gene and a chromosome are",
     "Explain how genes lead to traits"
    ],
    "teaser": "The code inside every cell.",
    "minutes": 9,
    "evidence": [
     {
      "id": "dna-read",
      "kind": "reading",
      "title": "DNA and genes",
      "minutes": 4,
      "blurb": "Describe the structure of DNA"
     },
     {
      "id": "dna-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "dna-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "alleles",
    "title": "Alleles: dominant and recessive",
    "goals": [
     "Say what an allele is",
     "Tell dominant from recessive alleles",
     "Explain genotype and phenotype"
    ],
    "teaser": "Why a trait can skip a generation.",
    "minutes": 9,
    "evidence": [
     {
      "id": "alleles-read",
      "kind": "reading",
      "title": "Alleles: dominant and recessive",
      "minutes": 4,
      "blurb": "Say what an allele is"
     },
     {
      "id": "alleles-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "alleles-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "punnett",
    "title": "Punnett squares",
    "goals": [
     "Complete a Punnett square",
     "Work out genotype and phenotype ratios",
     "Explain what the results mean in terms of probability"
    ],
    "teaser": "Predict the odds of each possible offspring.",
    "minutes": 9,
    "evidence": [
     {
      "id": "punnett-read",
      "kind": "reading",
      "title": "Punnett squares",
      "minutes": 4,
      "blurb": "Complete a Punnett square"
     },
     {
      "id": "punnett-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "punnett-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "selection",
    "title": "Natural selection",
    "goals": [
     "Describe the steps of natural selection",
     "Explain the role of variation and mutation",
     "Use examples such as peppered moths and antibiotic resistance"
    ],
    "teaser": "How populations change without anyone planning it.",
    "minutes": 9,
    "evidence": [
     {
      "id": "selection-read",
      "kind": "reading",
      "title": "Natural selection",
      "minutes": 4,
      "blurb": "Describe the steps of natural selection"
     },
     {
      "id": "selection-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "selection-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "evidence",
    "title": "Evidence for evolution",
    "goals": [
     "Describe several kinds of evidence for evolution",
     "Explain homologous structures",
     "Say what a scientific theory is"
    ],
    "teaser": "Fossils, anatomy, DNA and observations.",
    "minutes": 9,
    "evidence": [
     {
      "id": "evidence-read",
      "kind": "reading",
      "title": "Evidence for evolution",
      "minutes": 4,
      "blurb": "Describe several kinds of evidence for evolution"
     },
     {
      "id": "evidence-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "evidence-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   }
  ]
 },
 {
  "id": "quadratics-trig",
  "number": "163",
  "title": "The Case of the Curved Path",
  "topic": "Quadratics and trigonometry",
  "subject": "maths",
  "grade": 10,
  "tagline": "Solve quadratic equations, graph parabolas, and use angles to find lengths you cannot measure.",
  "hook": "A ball is thrown from the roof of a building and lands in a courtyard. A camera caught only the moment it landed and the angle of the sun on the wall. How high did the ball go? How tall is the building? With quadratics and trigonometry, you can work it out.",
  "goal": "Factorise and solve quadratic equations, sketch parabolas, and use sine, cosine and tangent to find unknown sides and angles.",
  "learn": [
   "Expand brackets and factorise quadratics",
   "Solve quadratic equations with the quadratic formula",
   "Sketch parabolas and find their key features",
   "Use sine, cosine and tangent in right triangles",
   "Find missing sides and angles in right triangles"
  ],
  "clues": [
   {
    "id": "factorising",
    "title": "Factorising quadratics",
    "goals": [
     "Expand two brackets",
     "Factorise a quadratic of the form x² + bx + c",
     "Solve a quadratic by factorising and using the zero-product rule"
    ],
    "teaser": "Break a quadratic into two brackets and solve it.",
    "minutes": 9,
    "evidence": [
     {
      "id": "factorising-read",
      "kind": "reading",
      "title": "Factorising quadratics",
      "minutes": 4,
      "blurb": "Expand two brackets"
     },
     {
      "id": "factorising-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "factorising-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "formula",
    "title": "The quadratic formula",
    "goals": [
     "Write a quadratic in the form ax² + bx + c = 0",
     "Use the quadratic formula to find solutions",
     "Use the discriminant to say how many real solutions there are"
    ],
    "teaser": "A formula that solves any quadratic equation.",
    "minutes": 9,
    "evidence": [
     {
      "id": "formula-read",
      "kind": "reading",
      "title": "The quadratic formula",
      "minutes": 4,
      "blurb": "Write a quadratic in the form ax² + bx + c = 0"
     },
     {
      "id": "formula-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "formula-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "parabolas",
    "title": "Graphing parabolas",
    "goals": [
     "Describe the shape of y = ax² + bx + c",
     "Find the roots, axis of symmetry, vertex and y-intercept",
     "Use a quadratic graph to answer a real-life question"
    ],
    "teaser": "The curve behind a thrown ball and a satellite dish.",
    "minutes": 9,
    "evidence": [
     {
      "id": "parabolas-read",
      "kind": "reading",
      "title": "Graphing parabolas",
      "minutes": 4,
      "blurb": "Describe the shape of y = ax² + bx + c"
     },
     {
      "id": "parabolas-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "parabolas-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "sohcahtoa",
    "title": "Sine, cosine and tangent",
    "goals": [
     "Label the opposite, adjacent and hypotenuse for an angle",
     "State sin, cos and tan as ratios",
     "Use a trig ratio to find a height"
    ],
    "teaser": "Three ratios that link angles and sides.",
    "minutes": 9,
    "evidence": [
     {
      "id": "sohcahtoa-read",
      "kind": "reading",
      "title": "Sine, cosine and tangent",
      "minutes": 4,
      "blurb": "Label the opposite, adjacent and hypotenuse for an angle"
     },
     {
      "id": "sohcahtoa-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "sohcahtoa-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "solving-triangles",
    "title": "Finding sides and angles with trig",
    "goals": [
     "Choose sin, cos or tan from what is known and what is wanted",
     "Find a missing side",
     "Find a missing angle using an inverse function"
    ],
    "teaser": "Choose the right ratio and solve.",
    "minutes": 9,
    "evidence": [
     {
      "id": "solving-triangles-read",
      "kind": "reading",
      "title": "Finding sides and angles with trig",
      "minutes": 4,
      "blurb": "Choose sin, cos or tan from what is known and what is wanted"
     },
     {
      "id": "solving-triangles-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "solving-triangles-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   }
  ]
 },
 {
  "id": "world-wars",
  "number": "171",
  "title": "The Case of the Unsent Letter",
  "topic": "The World Wars",
  "subject": "history",
  "grade": 10,
  "tagline": "Why the world went to war twice in thirty years, and what people learned from it.",
  "hook": "In an attic, someone finds a letter that was never sent. It is dated 1916, written in a muddy trench, and it asks the person at home a question: “Will it ever end?” To understand the writer's world, you must understand how a single shot in 1914 led to a war that would be followed by another.",
  "goal": "Explain the causes and key events of the two world wars, and what the world learned from them.",
  "learn": [
   "Explain the long-term causes and trigger of the First World War",
   "Describe trench warfare and why it caused a stalemate",
   "Explain how the peace settlement and the 1930s led to the Second World War",
   "Describe the main turning points of the Second World War",
   "Describe the Holocaust, and how the world responded"
  ],
  "clues": [
   {
    "id": "ww1-causes",
    "title": "The causes of World War I",
    "goals": [
     "Explain the four long-term causes known as MAIN",
     "Describe the alliance system",
     "Explain how the assassination in Sarajevo led to war"
    ],
    "teaser": "Long-term tensions, and one spark in Sarajevo.",
    "minutes": 9,
    "evidence": [
     {
      "id": "ww1-causes-read",
      "kind": "reading",
      "title": "The causes of World War I",
      "minutes": 4,
      "blurb": "Explain the four long-term causes known as MAIN"
     },
     {
      "id": "ww1-causes-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "ww1-causes-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "trenches",
    "title": "Trench warfare",
    "goals": [
     "Explain why trench warfare developed",
     "Describe conditions in the trenches",
     "Explain why attacks caused such heavy casualties"
    ],
    "teaser": "A stalemate on the Western Front, and life in the mud.",
    "minutes": 9,
    "evidence": [
     {
      "id": "trenches-read",
      "kind": "reading",
      "title": "Trench warfare",
      "minutes": 4,
      "blurb": "Explain why trench warfare developed"
     },
     {
      "id": "trenches-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "trenches-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "versailles",
    "title": "From Versailles to World War II",
    "goals": [
     "Describe the main terms of the Treaty of Versailles",
     "Explain why many Germans resented it",
     "Describe the steps that led to war in 1939"
    ],
    "teaser": "A harsh peace, a depression, and the road to a second war.",
    "minutes": 9,
    "evidence": [
     {
      "id": "versailles-read",
      "kind": "reading",
      "title": "From Versailles to World War II",
      "minutes": 4,
      "blurb": "Describe the main terms of the Treaty of Versailles"
     },
     {
      "id": "versailles-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "versailles-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "ww2-turning",
    "title": "World War II: turning points",
    "goals": [
     "Name the two sides and some key events",
     "Explain at least three turning points",
     "Say how and when the war ended"
    ],
    "teaser": "Key moments that changed the course of the war.",
    "minutes": 9,
    "evidence": [
     {
      "id": "ww2-turning-read",
      "kind": "reading",
      "title": "World War II: turning points",
      "minutes": 4,
      "blurb": "Name the two sides and some key events"
     },
     {
      "id": "ww2-turning-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "ww2-turning-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "holocaust",
    "title": "The Holocaust and its aftermath",
    "goals": [
     "Describe how the Nazi regime persecuted Jewish people step by step",
     "Say who else was persecuted, and that some people resisted and rescued",
     "Describe how the world responded after the war"
    ],
    "teaser": "Remembering the victims, and what the world did next.",
    "minutes": 9,
    "evidence": [
     {
      "id": "holocaust-read",
      "kind": "reading",
      "title": "The Holocaust and its aftermath",
      "minutes": 4,
      "blurb": "Describe how the Nazi regime persecuted Jewish people step by step"
     },
     {
      "id": "holocaust-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "holocaust-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   }
  ]
 },
 {
  "id": "climate-change",
  "number": "178",
  "title": "The Case of the Melting Evidence",
  "topic": "Climate change and sustainability",
  "subject": "geography",
  "grade": 10,
  "tagline": "How the greenhouse effect works, how we know the world is warming, and what can be done.",
  "hook": "A glacier that tourists once walked up has shrunk so far that the car park built beside it now sits miles from the ice. A museum label shows a photograph from a hundred years ago. What changed, and why? To solve this one, you will follow the evidence from the atmosphere to the ice.",
  "goal": "Explain the greenhouse effect, the evidence and causes of climate change, its impacts, and the main responses.",
  "learn": [
   "Explain the natural and enhanced greenhouse effect",
   "Describe the evidence that the climate is changing",
   "Explain the human causes of climate change",
   "Describe the main impacts on people and nature",
   "Tell mitigation from adaptation and give examples of each"
  ],
  "clues": [
   {
    "id": "greenhouse",
    "title": "The greenhouse effect",
    "goals": [
     "Explain how the natural greenhouse effect works",
     "Name the main greenhouse gases",
     "Explain the enhanced greenhouse effect"
    ],
    "teaser": "A natural blanket that is getting thicker.",
    "minutes": 9,
    "evidence": [
     {
      "id": "greenhouse-read",
      "kind": "reading",
      "title": "The greenhouse effect",
      "minutes": 4,
      "blurb": "Explain how the natural greenhouse effect works"
     },
     {
      "id": "greenhouse-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "greenhouse-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "evidence",
    "title": "Evidence of climate change",
    "goals": [
     "Describe several kinds of evidence for climate change",
     "Explain how ice cores give information about the past",
     "Explain why one cold winter does not disprove global warming"
    ],
    "teaser": "Thermometers, satellites, ice cores and rising seas all agree.",
    "minutes": 9,
    "evidence": [
     {
      "id": "evidence-read",
      "kind": "reading",
      "title": "Evidence of climate change",
      "minutes": 4,
      "blurb": "Describe several kinds of evidence for climate change"
     },
     {
      "id": "evidence-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "evidence-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "causes",
    "title": "What causes climate change",
    "goals": [
     "Name the main human sources of greenhouse gases",
     "Explain why natural factors do not explain recent warming",
     "Say what a carbon footprint is"
    ],
    "teaser": "The role of fossil fuels, forests and farming.",
    "minutes": 9,
    "evidence": [
     {
      "id": "causes-read",
      "kind": "reading",
      "title": "What causes climate change",
      "minutes": 4,
      "blurb": "Name the main human sources of greenhouse gases"
     },
     {
      "id": "causes-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "causes-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "impacts",
    "title": "Impacts of climate change",
    "goals": [
     "Describe the main physical impacts of warming",
     "Describe the effects on people and ecosystems",
     "Explain why impacts are unequal"
    ],
    "teaser": "Heat, rising seas, extreme weather and changing ecosystems.",
    "minutes": 9,
    "evidence": [
     {
      "id": "impacts-read",
      "kind": "reading",
      "title": "Impacts of climate change",
      "minutes": 4,
      "blurb": "Describe the main physical impacts of warming"
     },
     {
      "id": "impacts-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "impacts-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   },
   {
    "id": "solutions",
    "title": "Responding to climate change",
    "goals": [
     "Tell mitigation from adaptation and give examples",
     "Describe the aims of the Paris Agreement",
     "Explain what individuals, businesses and governments can do"
    ],
    "teaser": "Cutting emissions and preparing for change.",
    "minutes": 9,
    "evidence": [
     {
      "id": "solutions-read",
      "kind": "reading",
      "title": "Responding to climate change",
      "minutes": 4,
      "blurb": "Tell mitigation from adaptation and give examples"
     },
     {
      "id": "solutions-try",
      "kind": "reading",
      "title": "Try it",
      "minutes": 3,
      "blurb": "A worked example or short activity."
     },
     {
      "id": "solutions-practice",
      "kind": "practice",
      "title": "Check your understanding",
      "minutes": 2,
      "blurb": "Two quick practice questions."
     }
    ]
   }
  ]
 }
];

export const TOP_UP_CLUES: Record<string, ClueDef[]> = {
 "fractions": [
  {
   "id": "of-amount",
   "title": "Fractions of an amount",
   "goals": [
    "Explain finding a fraction of an amount as “divide, then multiply”",
    "Find a fraction of a whole number",
    "Solve simple word problems that use fractions of amounts"
   ],
   "teaser": "Find 3/4 of 24 students, or 2/5 of 50 minutes.",
   "minutes": 9,
   "evidence": [
    {
     "id": "of-amount-read",
     "kind": "reading",
     "title": "Fractions of an amount",
     "minutes": 4,
     "blurb": "Explain finding a fraction of an amount as “divide, then multiply”"
    },
    {
     "id": "of-amount-try",
     "kind": "reading",
     "title": "Try it",
     "minutes": 3,
     "blurb": "A worked example or short activity."
    },
    {
     "id": "of-amount-practice",
     "kind": "practice",
     "title": "Check your understanding",
     "minutes": 2,
     "blurb": "Two quick practice questions."
    }
   ]
  }
 ],
 "solar-system": [
  {
   "id": "seasons",
   "title": "Day, night and seasons",
   "goals": [
    "Explain day and night using Earth's spin",
    "Explain the seasons using the tilt of Earth's axis",
    "Say why the two hemispheres have opposite seasons"
   ],
   "teaser": "A spinning, tilted Earth makes day, night and the seasons.",
   "minutes": 9,
   "evidence": [
    {
     "id": "seasons-read",
     "kind": "reading",
     "title": "Day, night and seasons",
     "minutes": 4,
     "blurb": "Explain day and night using Earth's spin"
    },
    {
     "id": "seasons-try",
     "kind": "reading",
     "title": "Try it",
     "minutes": 3,
     "blurb": "A worked example or short activity."
    },
    {
     "id": "seasons-practice",
     "kind": "practice",
     "title": "Check your understanding",
     "minutes": 2,
     "blurb": "Two quick practice questions."
    }
   ]
  }
 ],
 "ancient-egypt": [
  {
   "id": "afterlife",
   "title": "Gods, mummies and the afterlife",
   "goals": [
    "Name some Egyptian gods and what they stood for",
    "Explain why Egyptians believed in an afterlife",
    "Describe the main steps of mummification"
   ],
   "teaser": "Why Egyptians preserved bodies and filled tombs with treasure.",
   "minutes": 9,
   "evidence": [
    {
     "id": "afterlife-read",
     "kind": "reading",
     "title": "Gods, mummies and the afterlife",
     "minutes": 4,
     "blurb": "Name some Egyptian gods and what they stood for"
    },
    {
     "id": "afterlife-try",
     "kind": "reading",
     "title": "Try it",
     "minutes": 3,
     "blurb": "A worked example or short activity."
    },
    {
     "id": "afterlife-practice",
     "kind": "practice",
     "title": "Check your understanding",
     "minutes": 2,
     "blurb": "Two quick practice questions."
    }
   ]
  }
 ],
 "shaking-ground": [
  {
   "id": "safety",
   "title": "Living with earthquakes and volcanoes",
   "goals": [
    "Say what to do during an earthquake",
    "Explain how buildings and warnings reduce harm",
    "Explain why millions of people live near volcanoes"
   ],
   "teaser": "How people prepare, stay safe and live near danger.",
   "minutes": 9,
   "evidence": [
    {
     "id": "safety-read",
     "kind": "reading",
     "title": "Living with earthquakes and volcanoes",
     "minutes": 4,
     "blurb": "Say what to do during an earthquake"
    },
    {
     "id": "safety-try",
     "kind": "reading",
     "title": "Try it",
     "minutes": 3,
     "blurb": "A worked example or short activity."
    },
    {
     "id": "safety-practice",
     "kind": "practice",
     "title": "Check your understanding",
     "minutes": 2,
     "blurb": "Two quick practice questions."
    }
   ]
  }
 ]
};
